// src/lib/constants/tools.ts
// Central registry of all tools — drives routing, SEO, and UI

export type ToolCategory =
  | 'image'
  | 'text'
  | 'developer'
  | 'converter'
  | 'generator'
  | 'calculator'
  | 'security'
  | 'seo'
  | 'network'
  | 'creative';

import { FAQ } from '@/lib/seo/json-ld';

export interface Tool {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  category: ToolCategory;
  subcategory?: string; // For grouping calculators and other tools into subcategories
  tags: string[];
  keywords: string[];
  icon: string;
  isNew?: boolean;
  isPopular?: boolean;
  relatedTools?: string[];
  phase: 1 | 2 | 3 | 4; // which phase this tool ships in
  faqs?: FAQ[]; // SEO FAQs for FAQPage schema
  howToUse?: string[]; // Custom how-to steps for this tool
  aboutContent?: string; // Enhanced about content (100-150 words)
}

export const TOOLS: Tool[] = [
  // ── Phase 2: Core Tools ──────────────────────────────────────────

  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress JPG, PNG, WebP without losing quality',
    description:
      'Compress and optimize images online for free. Reduce JPG, PNG, and WebP file sizes without losing quality. No upload required — works in your browser.',
    category: 'image',
    tags: ['compress', 'optimize', 'jpg', 'png', 'webp', 'image', 'reduce'],
    keywords: ['compress image online free', 'reduce image size', 'image optimizer'],
    icon: 'ImageDown',
    isPopular: true,
    relatedTools: ['image-resizer', 'image-converter', 'image-cropper'],
    phase: 2,
    faqs: [
      {
        question: 'How does image compression work without losing quality?',
        answer: 'Our tool uses advanced algorithms to optimize image data while preserving visual quality. It removes unnecessary metadata and applies smart compression techniques that reduce file size significantly while maintaining the image clarity.',
      },
      {
        question: 'Is my image data safe when using this tool?',
        answer: 'Absolutely. All image processing happens directly in your browser using JavaScript. Your images are never uploaded to any server, ensuring complete privacy and security.',
      },
      {
        question: 'What image formats are supported?',
        answer: 'We support JPG, PNG, and WebP formats. You can compress individual images or batch process multiple images at once.',
      },
      {
        question: 'Can I control the compression level?',
        answer: 'Yes, you can adjust the compression quality slider to balance between file size reduction and image quality according to your needs.',
      },
    ],
    howToUse: [
      'Upload your image by dragging and dropping or clicking the upload button',
      'Adjust the compression quality slider to your preferred level',
      'Preview the compressed image and compare file sizes',
      'Download your optimized image instantly',
    ],
    aboutContent: 'The Image Compressor is a powerful free online tool that reduces image file sizes while maintaining quality. Perfect for web developers, content creators, and anyone who needs to optimize images for faster website loading. Our compression algorithm intelligently removes unnecessary data and applies efficient encoding techniques. Use this tool to compress JPG, PNG, and WebP images without installing any software or uploading files to external servers.',
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    shortDescription: 'Create QR codes for URLs, text, WiFi, and more',
    description:
      'Generate QR codes for URLs, text, email, phone, and WiFi for free. Download as PNG or SVG. No sign-up required.',
    category: 'generator',
    tags: ['qr', 'qrcode', 'barcode', 'generate', 'url', 'wifi'],
    keywords: ['free QR code generator', 'create QR code online', 'QR code maker'],
    icon: 'QrCode',
    isPopular: true,
    relatedTools: ['barcode-generator', 'password-generator'],
    phase: 2,
    faqs: [
      {
        question: 'What types of QR codes can I generate?',
        answer: 'You can generate QR codes for URLs, plain text, email addresses, phone numbers, WiFi credentials, and more. Each type is optimized for its specific use case.',
      },
      {
        question: 'What file formats are available for download?',
        answer: 'QR codes can be downloaded as PNG (raster) or SVG (vector) formats. SVG is recommended for print materials as it can be scaled without quality loss.',
      },
      {
        question: 'Can I customize the QR code appearance?',
        answer: 'Yes, you can adjust the size, color, and error correction level of your QR code to match your branding or design requirements.',
      },
      {
        question: 'Are the generated QR codes free to use?',
        answer: 'Absolutely. All QR codes generated are completely free for both personal and commercial use with no watermarks or restrictions.',
      },
    ],
    howToUse: [
      'Select the type of QR code you want to create (URL, text, WiFi, etc.)',
      'Enter your content in the input field',
      'Customize the size, color, and other settings if desired',
      'Click generate and download your QR code in PNG or SVG format',
    ],
    aboutContent: 'The QR Code Generator is a versatile free online tool for creating custom QR codes for various purposes. Whether you need to share a website link, contact information, or WiFi credentials, this tool makes it simple. Perfect for marketers, business owners, and anyone who needs quick, scannable codes. Our generator supports multiple data types and offers both raster and vector output formats for maximum flexibility.',
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Generate strong, random, secure passwords',
    description:
      'Generate strong, random, secure passwords instantly. Customize length, symbols, numbers, and more. Free online password generator.',
    category: 'security',
    tags: ['password', 'security', 'random', 'secure', 'generate'],
    keywords: ['strong password generator', 'random password generator', 'secure password'],
    icon: 'KeyRound',
    isPopular: true,
    relatedTools: ['hash-generator', 'uuid-generator'],
    phase: 2,
    faqs: [
      {
        question: 'How secure are the generated passwords?',
        answer: 'Our password generator uses cryptographically secure random number generation to create truly unpredictable passwords. Each password is generated locally in your browser for maximum security.',
      },
      {
        question: 'What password length should I use?',
        answer: 'We recommend at least 16 characters for high-security applications. Longer passwords are exponentially more difficult to crack. Our generator supports up to 128 characters.',
      },
      {
        question: 'Should I include special characters and numbers?',
        answer: 'Yes, including a mix of uppercase letters, lowercase letters, numbers, and special characters significantly increases password strength by expanding the possible character combinations.',
      },
      {
        question: 'Are my passwords stored or sent anywhere?',
        answer: 'No. All password generation happens entirely in your browser using JavaScript. No data is ever sent to any server, ensuring your passwords remain completely private.',
      },
    ],
    howToUse: [
      'Set your desired password length using the slider (minimum 8 characters recommended)',
      'Select character types: uppercase, lowercase, numbers, and symbols',
      'Click the generate button to create a random password',
      'Copy the password to your clipboard using the copy button',
    ],
    aboutContent: 'The Password Generator is a essential security tool for creating strong, random passwords that protect your online accounts. Using weak or predictable passwords is a major security risk. Our generator creates cryptographically secure passwords with customizable length and complexity. Perfect for creating passwords for websites, applications, and services. All generation happens locally in your browser, ensuring your passwords are never stored or transmitted.',
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    shortDescription: 'Crop and resize images with custom aspect ratios',
    description:
      'Crop and resize images online for free. Supports custom ratios, square, 16:9, and more. Download cropped image instantly.',
    category: 'image',
    tags: ['crop', 'resize', 'cut', 'image', 'aspect ratio'],
    keywords: ['crop image online free', 'image crop tool', 'cut image online'],
    icon: 'Crop',
    relatedTools: ['image-compressor', 'image-resizer', 'image-converter'],
    phase: 2,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription: 'Format, validate, and beautify JSON online',
    description:
      'Format, beautify, and validate JSON online for free. Minify JSON, fix errors, and view JSON tree structure. No sign-up required.',
    category: 'developer',
    tags: ['json', 'format', 'validate', 'beautify', 'minify', 'developer'],
    keywords: ['JSON formatter online', 'JSON beautifier', 'validate JSON', 'format JSON'],
    icon: 'Braces',
    isPopular: true,
    relatedTools: ['base64-encoder', 'url-encoder', 'hash-generator'],
    phase: 2,
    faqs: [
      {
        question: 'What can I do with this JSON tool?',
        answer: 'You can format and beautify JSON for readability, validate JSON syntax to find errors, minify JSON to reduce file size, and view JSON data in a structured tree format.',
      },
      {
        question: 'How does JSON validation work?',
        answer: 'Our tool checks your JSON against the official JSON specification. It identifies syntax errors, missing commas, mismatched brackets, and other common issues with clear error messages.',
      },
      {
        question: 'Can I minify JSON for production use?',
        answer: 'Yes, our minify feature removes all whitespace and unnecessary characters to create compact JSON files perfect for API responses and production environments.',
      },
      {
        question: 'Is my JSON data secure?',
        answer: 'Absolutely. All JSON processing happens locally in your browser. Your data is never sent to any server, ensuring complete privacy and security for sensitive data.',
      },
    ],
    howToUse: [
      'Paste or type your JSON data into the input area',
      'Click "Format" to beautify or "Minify" to compress',
      'Use "Validate" to check for syntax errors',
      'Copy the formatted result to your clipboard',
    ],
    aboutContent: 'The JSON Formatter is an essential developer tool for working with JSON data. Whether you need to format messy JSON for readability, validate syntax, or minify for production, this tool handles it all. Perfect for web developers, API integrators, and anyone working with JSON data. Our validator provides clear error messages to help you debug quickly, and the tree view makes complex JSON structures easy to understand.',
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, sentences in real time',
    description:
      'Count words, characters, sentences, and paragraphs in real time. Free online word counter for writers, students, and bloggers.',
    category: 'text',
    tags: ['word', 'character', 'count', 'text', 'writer', 'sentence'],
    keywords: ['word counter online', 'character count', 'word count tool'],
    icon: 'AlignLeft',
    relatedTools: ['lorem-ipsum', 'case-converter', 'markdown-previewer'],
    phase: 2,
    faqs: [
      {
        question: 'What text metrics does this tool count?',
        answer: 'Our word counter tracks words, characters (with and without spaces), sentences, paragraphs, and reading time. It provides comprehensive text analysis for writers and editors.',
      },
      {
        question: 'Does this tool count words in real-time?',
        answer: 'Yes, the word counter updates instantly as you type or paste text. You can see the counts change in real-time, making it perfect for writing with specific word count requirements.',
      },
      {
        question: 'Can I use this for academic or professional writing?',
        answer: 'Absolutely. Our word counter is ideal for essays, reports, articles, and any writing with word limits. It accurately counts words according to standard conventions.',
      },
      {
        question: 'Is my text data private?',
        answer: 'Yes, all text processing happens entirely in your browser. Your content is never sent to any server, ensuring complete privacy for sensitive documents.',
      },
    ],
    howToUse: [
      'Type or paste your text into the input area',
      'View real-time word count, character count, and other metrics',
      'Use the analysis to meet word count requirements or improve readability',
      'Copy the results or clear the text to start over',
    ],
    aboutContent: 'The Word Counter is a versatile free online tool for writers, students, bloggers, and anyone who needs to track text metrics. Our tool provides real-time word count, character count, sentence count, paragraph count, and estimated reading time. Perfect for meeting essay requirements, social media character limits, or analyzing document length. All processing happens locally in your browser for complete privacy.',
  },
  {
    slug: 'color-palette',
    name: 'Color Palette Extractor',
    shortDescription: 'Extract dominant colors from any image',
    description:
      'Upload an image and instantly extract its dominant color palette. Get HEX, RGB, and HSL codes. Free, no sign-up required.',
    category: 'image',
    tags: ['color', 'palette', 'extract', 'image', 'hex', 'rgb'],
    keywords: ['color palette from image', 'extract colors from image', 'dominant colors'],
    icon: 'Palette',
    relatedTools: ['image-compressor', 'image-cropper', 'color-picker'],
    phase: 2,
    faqs: [
      {
        question: 'How does color extraction work?',
        answer: 'Our tool analyzes the pixels in your image to identify the most frequently occurring colors. It uses advanced algorithms to extract dominant colors while ignoring minor variations and noise.',
      },
      {
        question: 'What color formats are supported?',
        answer: 'We provide colors in multiple formats including HEX (for web), RGB (for digital design), and HSL (for color manipulation). You can copy any format with one click.',
      },
      {
        question: 'Can I upload any type of image?',
        answer: 'Yes, we support all common image formats including JPG, PNG, WebP, GIF, and more. The tool processes images entirely in your browser for maximum privacy.',
      },
      {
        question: 'How many colors will be extracted?',
        answer: 'By default, we extract the 10 most dominant colors from your image. You can adjust this number to get fewer or more colors depending on your needs.',
      },
    ],
    howToUse: [
      'Upload an image by dragging and dropping or clicking the upload button',
      'The tool automatically extracts dominant colors from your image',
      'View the color palette with HEX, RGB, and HSL values',
      'Click on any color to copy it to your clipboard',
    ],
    aboutContent: 'The Color Palette Extractor is a powerful free online tool for designers, developers, and anyone working with colors. Simply upload an image and instantly extract the dominant colors to create beautiful color schemes. Perfect for website design, branding, art projects, and color inspiration. Our tool provides colors in multiple formats and processes images locally for complete privacy.',
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder / Decoder',
    shortDescription: 'Encode and decode text, files, and images to Base64',
    description:
      'Encode text or files to Base64 and decode Base64 strings online for free. Supports text, images, and files with instant conversion.',
    category: 'developer',
    tags: ['base64', 'encode', 'decode', 'developer', 'convert'],
    keywords: ['base64 encode online', 'base64 decoder', 'text to base64'],
    icon: 'Binary',
    relatedTools: ['url-encoder', 'hash-generator', 'json-formatter'],
    phase: 2,
  },

  // ── Phase 3: Extended Tools ───────────────────────────────────────

  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to any width and height online for free',
    description: 'Resize images to any width and height online for free. Maintain aspect ratio or set custom dimensions. Download resized images instantly.',
    category: 'image',
    tags: ['resize', 'image', 'dimension', 'scale', 'width', 'height'],
    keywords: ['resize image online free', 'change image size', 'image dimensions', 'resize photo', 'scale image'],
    icon: 'Maximize',
    relatedTools: ['image-compressor', 'image-cropper'],
    phase: 3,
  },
  {
    slug: 'image-metadata-remover',
    name: 'Image Metadata Remover',
    shortDescription: 'Remove EXIF metadata and GPS data from images',
    description: 'Remove EXIF metadata, GPS location, and hidden data from images online for free. Protect your privacy by stripping image metadata directly in your browser.',
    category: 'image',
    tags: ['metadata', 'exif', 'gps', 'privacy', 'remove', 'clean'],
    keywords: ['remove image metadata online free', 'remove exif data', 'strip image metadata', 'clean image info', 'remove gps from photos'],
    icon: 'ShieldCheck',
    relatedTools: ['image-compressor', 'image-resizer'],
    phase: 3,
  },
  {
    slug: 'image-batch-resizer',
    name: 'Image Batch Resizer',
    shortDescription: 'Resize multiple images at once online for free',
    description: 'Resize multiple images at once online for free. Batch resize JPG, PNG, WebP files with custom dimensions, percentage scaling, or presets. Download as ZIP.',
    category: 'image',
    tags: ['batch', 'resize', 'multiple', 'bulk', 'image'],
    keywords: ['batch resize images online free', 'resize multiple images', 'bulk image resizer', 'batch image resize', 'resize photos in bulk'],
    icon: 'Layers',
    relatedTools: ['image-resizer', 'image-compressor'],
    phase: 3,
  },
  {
    slug: 'image-converter',
    name: 'Image Format Converter',
    shortDescription: 'Convert between JPG, PNG, WebP, GIF formats',
    description: 'Convert images between JPG, PNG, WebP, and GIF formats online for free. Fast browser-based conversion with no server uploads required.',
    category: 'image',
    tags: ['convert', 'format', 'jpg', 'png', 'webp', 'image'],
    keywords: ['image format converter', 'convert png to jpg', 'webp converter'],
    icon: 'RefreshCw',
    relatedTools: ['image-compressor', 'image-resizer'],
    phase: 3,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    shortDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 cryptographic hashes online for free. Instant hash generation with no data sent to server.',
    category: 'security',
    tags: ['hash', 'md5', 'sha256', 'sha1', 'sha512', 'crypto', 'security'],
    keywords: ['hash generator online', 'MD5 hash', 'SHA-256 generator', 'SHA-1 hash', 'cryptographic hash'],
    icon: 'Hash',
    relatedTools: ['password-generator', 'base64-encoder'],
    phase: 3,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder / Decoder',
    shortDescription: 'Encode and decode URL strings',
    description: 'Encode and decode URL strings and query parameters online for free. Handle special characters and percent-encoding for web development.',
    category: 'developer',
    tags: ['url', 'encode', 'decode', 'percent', 'developer'],
    keywords: ['URL encoder online', 'URL decoder', 'percent encode'],
    icon: 'Link',
    relatedTools: ['base64-encoder', 'json-formatter'],
    phase: 3,
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    shortDescription: 'Convert length, weight, temperature, and more',
    description: 'Convert between units of length, weight, temperature, area, speed, and more. Free online unit converter.',
    category: 'converter',
    tags: ['unit', 'convert', 'length', 'weight', 'temperature'],
    keywords: ['unit converter online', 'length converter', 'weight converter'],
    icon: 'ArrowLeftRight',
    relatedTools: [],
    phase: 3,
    faqs: [
      {
        question: 'What unit categories are supported?',
        answer: 'Our unit converter supports length, weight, temperature, area, volume, speed, time, data storage, and more. We regularly add new unit categories based on user feedback.',
      },
      {
        question: 'How accurate are the conversions?',
        answer: 'Our conversions use precise mathematical formulas and standard conversion factors. The results are accurate to multiple decimal places for scientific and engineering applications.',
      },
      {
        question: 'Can I convert multiple values at once?',
        answer: 'Yes, you can convert as many values as you need. Simply enter a value and select the units, and the conversion happens instantly. You can then change the value and units for additional conversions.',
      },
      {
        question: 'Is this tool free to use?',
        answer: 'Absolutely. Our unit converter is completely free with no limitations, subscriptions, or hidden fees. Use it as often as you need for personal or commercial purposes.',
      },
    ],
    howToUse: [
      'Select the unit category you want to convert (length, weight, temperature, etc.)',
      'Enter the value you want to convert',
      'Select the original unit and target unit from the dropdowns',
      'View the converted result instantly',
    ],
    aboutContent: 'The Unit Converter is a comprehensive free online tool for converting between different measurement units. Whether you need to convert metric to imperial, calculate temperature differences, or convert data storage units, this tool handles it all. Perfect for students, engineers, scientists, and everyday conversions. Our converter supports multiple categories and provides instant, accurate results.',
  },
  {
    slug: 'markdown-previewer',
    name: 'Markdown Previewer',
    shortDescription: 'Write and preview Markdown in real time',
    description: 'Write Markdown and see a live preview side by side. Supports GitHub Flavored Markdown with syntax highlighting and instant rendering.',
    category: 'text',
    tags: ['markdown', 'preview', 'text', 'editor', 'github'],
    keywords: ['markdown previewer online', 'markdown editor', 'live markdown preview'],
    icon: 'FileText',
    relatedTools: ['word-counter', 'lorem-ipsum'],
    phase: 3,
    faqs: [
      {
        question: 'What Markdown syntax is supported?',
        answer: 'Our previewer supports GitHub Flavored Markdown (GFM), including tables, task lists, strikethrough, autolinks, and more. It also supports standard Markdown syntax like headers, lists, links, images, and code blocks.',
      },
      {
        question: 'Can I export the rendered Markdown?',
        answer: 'Yes, you can copy the rendered HTML or export it. This is perfect for using Markdown content in websites, emails, or documents that support HTML.',
      },
      {
        question: 'Is my content saved or stored anywhere?',
        answer: 'No, all content stays in your browser. Nothing is sent to servers or stored in databases. Your Markdown content remains completely private and secure.',
      },
      {
        question: 'Can I use syntax highlighting for code blocks?',
        answer: 'Yes, our previewer supports syntax highlighting for code blocks. Simply specify the language after the opening backticks (e.g., ```javascript) and your code will be beautifully highlighted.',
      },
    ],
    howToUse: [
      'Type or paste your Markdown content in the left editor panel',
      'See the live rendered preview in the right panel',
      'Use the toolbar buttons for common Markdown formatting',
      'Copy the HTML or download when finished',
    ],
    aboutContent: 'The Markdown Previewer is an essential tool for writers, developers, and content creators. Write Markdown syntax and see a live preview instantly, making it easy to format documents, blog posts, and technical documentation. Our tool supports GitHub Flavored Markdown with syntax highlighting for code blocks. Perfect for README files, documentation, and any Markdown-based content.',
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate placeholder text for designs',
    description: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences, or paragraphs. Perfect for designs and mockups.',
    category: 'generator',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'filler'],
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator', 'lorem ipsum text', 'filler text'],
    icon: 'Type',
    relatedTools: ['word-counter', 'markdown-previewer'],
    phase: 3,
    faqs: [
      {
        question: 'What is Lorem Ipsum text?',
        answer: 'Lorem Ipsum is standard placeholder text used in printing and typesetting. It has been the industry standard for centuries and helps designers focus on layout without being distracted by meaningful content.',
      },
      {
        question: 'Can I customize the amount of text generated?',
        answer: 'Yes, you can choose to generate a specific number of words, sentences, or paragraphs. You can also generate text that fits within a specific character limit for your design needs.',
      },
      {
        question: 'Is the generated text unique each time?',
        answer: 'Each time you generate text, it creates a new random variation while maintaining the classic Lorem Ipsum structure. This gives you variety while keeping the authentic look and feel.',
      },
      {
        question: 'Can I use this for commercial projects?',
        answer: 'Absolutely. Lorem Ipsum text is in the public domain and free to use for any purpose, personal or commercial. Our generator makes it easy to get the exact amount you need.',
      },
    ],
    howToUse: [
      'Select the type of text you want (words, sentences, or paragraphs)',
      'Specify the quantity or let it generate a standard amount',
      'Click generate to create your placeholder text',
      'Copy the text to use in your designs or mockups',
    ],
    aboutContent: 'The Lorem Ipsum Generator is the perfect tool for designers, developers, and anyone needing placeholder text. Create realistic dummy text for website mockups, print designs, and prototypes. Our generator allows you to control the amount and type of text, giving you exactly what you need for your project. Lorem Ipsum has been the standard placeholder text for centuries, and our tool makes it easy to use.',
  },

  // ── Phase 3: Developer Tools (Extended) ───────────────────────────────

  {
    slug: 'json-to-csv',
    name: 'JSON to CSV Converter',
    shortDescription: 'Convert JSON data to CSV format',
    description: 'Convert JSON arrays and objects to CSV format online for free. Download converted CSV files instantly.',
    category: 'developer',
    tags: ['json', 'csv', 'convert', 'export', 'data'],
    keywords: ['json to csv converter', 'convert json to csv', 'json csv export'],
    icon: 'FileSpreadsheet',
    relatedTools: ['json-formatter', 'json-diff'],
    phase: 3,
  },
  {
    slug: 'json-diff',
    name: 'JSON Diff Comparator',
    shortDescription: 'Compare two JSON files and find differences',
    description: 'Compare two JSON objects and visualize differences. Highlight added, removed, and modified fields.',
    category: 'developer',
    tags: ['json', 'diff', 'compare', 'difference', 'change'],
    keywords: ['json diff', 'compare json', 'json difference checker'],
    icon: 'GitCompare',
    relatedTools: ['json-formatter', 'json-to-csv'],
    phase: 3,
  },
  {
    slug: 'json-path-finder',
    name: 'JSON Path Finder',
    shortDescription: 'Find and extract values from JSON using JSONPath',
    description: 'Query JSON data using JSONPath expressions. Extract specific values and paths from complex JSON structures.',
    category: 'developer',
    tags: ['json', 'path', 'query', 'extract', 'jsonpath'],
    keywords: ['json path finder', 'jsonpath query', 'extract json values'],
    icon: 'Search',
    relatedTools: ['json-formatter', 'json-filter'],
    phase: 3,
  },
  {
    slug: 'json-escape',
    name: 'JSON Escape / Unescape',
    shortDescription: 'Escape and unescape JSON strings',
    description: 'Escape special characters in JSON strings and unescape escaped JSON. Handle quotes, backslashes, and Unicode.',
    category: 'developer',
    tags: ['json', 'escape', 'unescape', 'string', 'special characters'],
    keywords: ['json escape', 'json unescape', 'escape json string'],
    icon: 'Quote',
    relatedTools: ['json-formatter', 'json-stringify'],
    phase: 3,
  },
  {
    slug: 'json-stringify',
    name: 'JSON Stringify Tool',
    shortDescription: 'Convert JavaScript objects to JSON strings',
    description: 'Convert JavaScript objects to JSON strings with customizable spacing and formatting. Handle circular references.',
    category: 'developer',
    tags: ['json', 'stringify', 'object', 'convert', 'javascript'],
    keywords: ['json stringify', 'object to json', 'javascript to json'],
    icon: 'Braces',
    relatedTools: ['json-formatter', 'json-parse'],
    phase: 3,
  },
  {
    slug: 'json-parse',
    name: 'JSON Parse Tool',
    shortDescription: 'Parse JSON strings into JavaScript objects',
    description: 'Parse JSON strings into readable JavaScript objects. Validate JSON syntax and view parsed structure.',
    category: 'developer',
    tags: ['json', 'parse', 'validate', 'object', 'syntax'],
    keywords: ['json parse', 'parse json string', 'json validator'],
    icon: 'Code2',
    relatedTools: ['json-formatter', 'json-stringify'],
    phase: 3,
  },
  {
    slug: 'json-filter',
    name: 'JSON Filter Tool',
    shortDescription: 'Filter JSON data by keys and values',
    description: 'Filter JSON arrays and objects by keys, values, or custom conditions. Extract specific data from large JSON.',
    category: 'developer',
    tags: ['json', 'filter', 'query', 'extract', 'search'],
    keywords: ['json filter', 'filter json data', 'query json'],
    icon: 'Filter',
    relatedTools: ['json-formatter', 'json-path-finder'],
    phase: 3,
  },
  {
    slug: 'json-schema-visualizer',
    name: 'JSON Schema Visualizer',
    shortDescription: 'Visualize JSON Schema structure and validation',
    description: 'Visualize JSON Schema definitions and validate JSON against schemas. View schema structure in tree format.',
    category: 'developer',
    tags: ['json', 'schema', 'visualize', 'validate', 'structure'],
    keywords: ['json schema visualizer', 'json schema validator', 'view json schema'],
    icon: 'Network',
    relatedTools: ['json-formatter', 'json-parse'],
    phase: 3,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortDescription: 'Test regular expressions with real-time matching',
    description: 'Test regular expressions against text in real time. Highlight matches, capture groups, and replace patterns.',
    category: 'developer',
    tags: ['regex', 'regular expression', 'test', 'match', 'pattern'],
    keywords: ['regex tester', 'regular expression tester', 'test regex online'],
    icon: 'Regex',
    relatedTools: ['regex-explainer'],
    phase: 3,
  },
  {
    slug: 'regex-explainer',
    name: 'Regex Explainer',
    shortDescription: 'Explain regular expressions in plain English',
    description: 'Break down regular expressions and explain each part in plain English. Understand complex regex patterns.',
    category: 'developer',
    tags: ['regex', 'regular expression', 'explain', 'learn', 'documentation'],
    keywords: ['regex explainer', 'explain regex', 'regex documentation'],
    icon: 'BookOpen',
    relatedTools: ['regex-tester'],
    phase: 3,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortDescription: 'Generate UUID v4 and other UUID versions',
    description: 'Generate UUID v4, v1, and other versions. Create bulk UUIDs and copy to clipboard instantly.',
    category: 'developer',
    tags: ['uuid', 'guid', 'generate', 'identifier', 'unique'],
    keywords: ['uuid generator', 'generate uuid', 'uuid v4'],
    icon: 'Fingerprint',
    relatedTools: ['hash-generator', 'password-generator'],
    phase: 3,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    shortDescription: 'Decode and verify JSON Web Tokens',
    description: 'Decode JWT tokens to view header, payload, and signature. Verify token structure and expiration.',
    category: 'developer',
    tags: ['jwt', 'json web token', 'decode', 'verify', 'token'],
    keywords: ['jwt decoder', 'decode jwt', 'jwt token decoder'],
    icon: 'Lock',
    relatedTools: ['base64-encoder', 'hash-generator'],
    phase: 3,
  },
  {
    slug: 'string-converter',
    name: 'String Converter',
    shortDescription: 'Convert between string formats (camelCase, snake_case, etc.)',
    description: 'Convert string cases between camelCase, snake_case, kebab-case, PascalCase, and more.',
    category: 'developer',
    tags: ['string', 'convert', 'case', 'format', 'transform'],
    keywords: ['string converter', 'case converter', 'convert string case'],
    icon: 'TextCase',
    relatedTools: ['json-formatter', 'url-encoder'],
    phase: 3,
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format and beautify SQL queries',
    description: 'Format SQL queries with proper indentation and syntax highlighting. Support for MySQL, PostgreSQL, and more. Free SQL beautifier for developers.',
    category: 'developer',
    tags: ['sql', 'format', 'beautify', 'query', 'database'],
    keywords: ['sql formatter', 'format sql', 'sql beautifier'],
    icon: 'Database',
    relatedTools: ['json-formatter', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortDescription: 'Convert Markdown to HTML',
    description: 'Convert Markdown text to HTML code. Supports GitHub Flavored Markdown and common syntax. Free Markdown to HTML converter for web content.',
    category: 'developer',
    tags: ['markdown', 'html', 'convert', 'markup', 'generate'],
    keywords: ['markdown to html', 'convert markdown', 'markdown html converter'],
    icon: 'FileCode',
    relatedTools: ['markdown-previewer', 'html-viewer'],
    phase: 3,
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    shortDescription: 'Compare two text blocks and find differences',
    description: 'Compare two text blocks and highlight differences. View added, removed, and modified lines side by side.',
    category: 'developer',
    tags: ['text', 'diff', 'compare', 'difference', 'change'],
    keywords: ['text diff', 'compare text', 'text difference checker'],
    icon: 'GitCompareArrows',
    relatedTools: ['json-diff', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'html-viewer',
    name: 'HTML Viewer & Live Preview',
    shortDescription: 'View and preview HTML code in real time',
    description: 'Write HTML code and see live preview instantly. Test HTML snippets and visualize rendered output.',
    category: 'developer',
    tags: ['html', 'preview', 'viewer', 'render', 'live'],
    keywords: ['html viewer', 'html preview', 'live html preview'],
    icon: 'Eye',
    relatedTools: ['markdown-to-html', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'code-minifier',
    name: 'Code Minifier',
    shortDescription: 'Minify JavaScript, CSS, and HTML code',
    description: 'Minify JavaScript, CSS, and HTML code to reduce file size. Remove whitespace and comments automatically.',
    category: 'developer',
    tags: ['code', 'minify', 'compress', 'optimize', 'reduce'],
    keywords: ['code minifier', 'minify javascript', 'minify css'],
    icon: 'Minimize2',
    relatedTools: ['json-formatter', 'sql-formatter'],
    phase: 3,
  },
  {
    slug: 'cron-builder',
    name: 'Cron Expression Builder',
    shortDescription: 'Build and test cron expressions visually',
    description: 'Build cron expressions with a visual interface. Test cron schedules and view next execution times.',
    category: 'developer',
    tags: ['cron', 'schedule', 'expression', 'builder', 'time'],
    keywords: ['cron builder', 'cron expression', 'cron schedule builder'],
    icon: 'Clock',
    relatedTools: ['uuid-generator'],
    phase: 3,
  },
  {
    slug: 'css-grid-generator',
    name: 'CSS Grid Generator',
    shortDescription: 'Generate CSS Grid layouts visually',
    description: 'Generate CSS Grid layouts with a visual builder. Configure columns, rows, gaps, and areas interactively.',
    category: 'developer',
    tags: ['css', 'grid', 'layout', 'generator', 'visual'],
    keywords: ['css grid generator', 'css grid layout', 'grid builder'],
    icon: 'Grid3x3',
    relatedTools: ['html-viewer', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'har-viewer',
    name: 'HAR Viewer',
    shortDescription: 'View and analyze HTTP Archive (HAR) files',
    description: 'Upload and analyze HAR files to view network requests, responses, timings, and headers.',
    category: 'developer',
    tags: ['har', 'http', 'archive', 'network', 'analyze'],
    keywords: ['har viewer', 'har file viewer', 'http archive viewer'],
    icon: 'FileJson',
    relatedTools: ['json-formatter', 'json-diff'],
    phase: 3,
  },
  {
    slug: 'security-header-analyzer',
    name: 'Security Header Analyzer',
    shortDescription: 'Analyze HTTP security headers',
    description: 'Analyze HTTP security headers like CSP, HSTS, X-Frame-Options. Get recommendations for improving security.',
    category: 'developer',
    tags: ['security', 'headers', 'http', 'analyze', 'csp'],
    keywords: ['security header analyzer', 'http security headers', 'csp analyzer'],
    icon: 'ShieldCheck',
    relatedTools: ['jwt-decoder', 'hash-generator'],
    phase: 3,
  },

  // ── SEO Tools ─────────────────────────────────────────────────────────────

  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    shortDescription: 'Generate SEO meta tags for your website',
    description: 'Generate meta tags for your website instantly. Create title, description, keywords, Open Graph, Twitter Card, and other SEO meta tags for free.',
    category: 'seo',
    tags: ['meta', 'tags', 'seo', 'open graph', 'twitter card'],
    keywords: ['meta tag generator', 'meta tags creator', 'SEO meta tags', 'HTML meta tags generator'],
    icon: 'Tag',
    relatedTools: ['open-graph-preview-generator', 'serp-snippet-preview'],
    phase: 3,
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    shortDescription: 'Analyze keyword usage in your content',
    description: 'Check keyword density in your content for free. Analyze word frequency, keyword repetition, and optimize your content for SEO.',
    category: 'seo',
    tags: ['keyword', 'density', 'seo', 'content', 'analysis'],
    keywords: ['keyword density checker', 'keyword analyzer', 'word frequency counter', 'SEO keyword analysis'],
    icon: 'BarChart3',
    relatedTools: ['readability-checker', 'title-description-length-checker'],
    phase: 3,
  },
  {
    slug: 'sitemap-generator',
    name: 'Sitemap Generator',
    shortDescription: 'Create XML sitemaps for search engines',
    description: 'Generate XML sitemaps for your website instantly. Add URLs, set priorities, change frequencies, and download valid sitemap files for free.',
    category: 'seo',
    tags: ['sitemap', 'xml', 'seo', 'search engine', 'indexing'],
    keywords: ['sitemap generator', 'XML sitemap creator', 'sitemap builder', 'Google sitemap generator'],
    icon: 'FileJson',
    relatedTools: ['robots-txt-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder (SEO)',
    shortDescription: 'Encode and decode URLs with SEO suggestions',
    description: 'Encode and decode URLs for SEO. Clean up URL parameters, fix special characters, and ensure your URLs are search engine friendly.',
    category: 'seo',
    tags: ['url', 'encode', 'decode', 'seo', 'clean'],
    keywords: ['URL encoder decoder SEO', 'URL cleaner', 'SEO URL tool', 'encode decode URL'],
    icon: 'Link',
    relatedTools: ['url-parameter-cleaner', 'sitemap-generator'],
    phase: 3,
  },
  {
    slug: 'open-graph-preview-generator',
    name: 'Open Graph Preview Generator',
    shortDescription: 'Test how your links appear on social media',
    description: 'Preview how your website appears on social media. Test Open Graph tags, see Facebook and LinkedIn previews, and optimize your social sharing.',
    category: 'seo',
    tags: ['open graph', 'og', 'social media', 'preview', 'facebook'],
    keywords: ['Open Graph preview generator', 'OG tag tester', 'social media preview', 'Facebook link preview'],
    icon: 'Eye',
    relatedTools: ['meta-tag-generator', 'open-graph-image-generator'],
    phase: 3,
  },
  {
    slug: 'open-graph-image-generator',
    name: 'Open Graph Image Generator',
    shortDescription: 'Create custom OG images for social sharing',
    description: 'Generate Open Graph images for social media sharing. Create custom OG images with your branding, text, and colors for free.',
    category: 'seo',
    tags: ['open graph', 'og', 'image', 'social media', 'generator'],
    keywords: ['Open Graph image generator', 'OG image creator', 'social media image generator', 'Facebook image maker'],
    icon: 'ImagePlus',
    relatedTools: ['open-graph-preview-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'serp-snippet-preview',
    name: 'SERP Snippet Preview',
    shortDescription: 'Preview Google search results appearance',
    description: 'Preview how your website appears in Google search results. Test title tags, meta descriptions, and optimize your SERP snippets for SEO.',
    category: 'seo',
    tags: ['serp', 'google', 'search', 'preview', 'snippet'],
    keywords: ['SERP snippet preview', 'Google search preview', 'SERP simulator', 'title tag preview'],
    icon: 'Search',
    relatedTools: ['title-description-length-checker', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'title-description-length-checker',
    name: 'Title & Description Checker',
    shortDescription: 'Check meta tag character limits for SEO',
    description: 'Check title tag and meta description length for SEO. Ensure your meta tags are within optimal character limits for Google and other search engines.',
    category: 'seo',
    tags: ['title', 'description', 'length', 'seo', 'meta'],
    keywords: ['title description length checker', 'meta tag length checker', 'SEO title analyzer', 'meta description counter'],
    icon: 'Ruler',
    relatedTools: ['serp-snippet-preview', 'keyword-density-checker'],
    phase: 3,
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    shortDescription: 'Create robots.txt files for crawler control',
    description: 'Generate robots.txt files for your website instantly. Control crawler access, set sitemap location, and manage SEO indexing for free.',
    category: 'seo',
    tags: ['robots', 'txt', 'crawler', 'seo', 'sitemap'],
    keywords: ['robots.txt generator', 'robots.txt creator', 'crawler control', 'SEO robots file'],
    icon: 'FileCode',
    relatedTools: ['sitemap-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'readability-checker',
    name: 'Readability Checker',
    shortDescription: 'Analyze text readability score',
    description: 'Check text readability score and analyze content quality. Calculate Flesch-Kincaid, Gunning Fog, and other readability metrics for SEO.',
    category: 'seo',
    tags: ['readability', 'text', 'seo', 'content', 'analysis'],
    keywords: ['readability checker', 'text readability analyzer', 'Flesch Kincaid score', 'content readability test'],
    icon: 'BookOpen',
    relatedTools: ['keyword-density-checker', 'title-description-length-checker'],
    phase: 3,
  },
  {
    slug: 'url-parameter-cleaner',
    name: 'URL Parameter Cleaner',
    shortDescription: 'Remove tracking parameters from URLs',
    description: 'Clean URLs by removing tracking parameters, UTM tags, and unnecessary query strings. Create clean, SEO-friendly URLs for free.',
    category: 'seo',
    tags: ['url', 'parameter', 'clean', 'tracking', 'utm'],
    keywords: ['URL parameter cleaner', 'URL cleaner', 'remove UTM parameters', 'strip tracking parameters'],
    icon: 'Filter',
    relatedTools: ['url-encoder-decoder', 'sitemap-generator'],
    phase: 3,
  },

  // ── Network Tools ─────────────────────────────────────────────────────────────

  {
    slug: 'internet-speed-test',
    name: 'Internet Speed Test',
    shortDescription: 'Check download & upload speed, latency, and jitter',
    description: 'Test your internet connection speed with our free online speed test. Measure download, upload, latency, and jitter using Cloudflare\'s network.',
    category: 'network',
    tags: ['speed', 'test', 'internet', 'bandwidth', 'latency', 'jitter'],
    keywords: ['internet speed test', 'network speed test', 'bandwidth test', 'connection speed', 'download speed', 'upload speed'],
    icon: 'Gauge',
    isPopular: true,
    relatedTools: ['ping-tool', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'address-lookup',
    name: 'IP Address Lookup',
    shortDescription: 'Get location, ISP, and timezone info for any IP',
    description: 'Lookup any IP address to find location, ISP, timezone, and more. Free IP geolocation service using ipapi.co for network analysis.',
    category: 'network',
    tags: ['ip', 'address', 'lookup', 'geolocation', 'location', 'isp'],
    keywords: ['IP address lookup', 'IP geolocation', 'find IP location', 'IP info', 'ISP lookup', 'IP tracker'],
    icon: 'MapPin',
    relatedTools: ['dns-lookup', 'whois-lookup'],
    phase: 3,
  },
  {
    slug: 'dns-lookup',
    name: 'DNS Lookup',
    shortDescription: 'Query DNS records for any domain',
    description: 'Perform DNS lookups for A, AAAA, MX, TXT, NS, CNAME records using Google\'s DNS API. Free DNS query tool for domain troubleshooting.',
    category: 'network',
    tags: ['dns', 'lookup', 'query', 'records', 'domain', 'nslookup'],
    keywords: ['DNS lookup', 'DNS query', 'DNS records', 'dig online', 'nslookup', 'DNS checker'],
    icon: 'Server',
    relatedTools: ['address-lookup', 'whois-lookup'],
    phase: 3,
  },
  {
    slug: 'http-headers-checker',
    name: 'HTTP Headers Checker',
    shortDescription: 'View and analyze HTTP response headers',
    description: 'Check HTTP response headers for any URL. View security headers, caching, content type, and more using AllOrigins API. Free HTTP header analyzer.',
    category: 'network',
    tags: ['http', 'headers', 'response', 'security', 'analyze'],
    keywords: ['HTTP headers checker', 'response headers', 'HTTP header analyzer', 'view headers', 'security headers'],
    icon: 'FileText',
    relatedTools: ['ssl-certificate-checker', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'ssl-certificate-checker',
    name: 'SSL Certificate Checker',
    shortDescription: 'Verify SSL/TLS certificates and security ratings',
    description: 'Check SSL certificate details, expiration, and security rating for any domain using SSL Labs API. Free SSL checker for website security.',
    category: 'network',
    tags: ['ssl', 'certificate', 'tls', 'security', 'verify', 'expiry'],
    keywords: ['SSL certificate checker', 'SSL verification', 'TLS certificate', 'SSL test', 'certificate analyzer', 'SSL expiry'],
    icon: 'ShieldCheck',
    relatedTools: ['http-headers-checker', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'ping-tool',
    name: 'Ping Tool',
    shortDescription: 'Test network latency and connectivity',
    description: 'Ping any host or IP address to test network connectivity and measure latency. Free online ping tool with packet loss detection.',
    category: 'network',
    tags: ['ping', 'network', 'latency', 'connectivity', 'test', 'packet loss'],
    keywords: ['ping tool', 'network ping', 'latency test', 'ping online', 'connectivity test', 'packet loss'],
    icon: 'Activity',
    relatedTools: ['internet-speed-test', 'port-checker'],
    phase: 3,
  },
  {
    slug: 'port-checker',
    name: 'Port Checker',
    shortDescription: 'Check if ports are open or closed on servers',
    description: 'Check if a port is open or closed on any server. Test common ports (80, 443, 22, 21, etc.) or custom ports. Free port scanner.',
    category: 'network',
    tags: ['port', 'checker', 'scanner', 'network', 'tcp', 'open'],
    keywords: ['port checker', 'open port scanner', 'port test', 'network port check', 'TCP port checker'],
    icon: 'Server',
    relatedTools: ['ping-tool', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'whois-lookup',
    name: 'WHOIS Lookup',
    shortDescription: 'Get domain registration and owner information',
    description: 'Lookup WHOIS information for any domain. Find registrar, creation date, expiration, and owner details using WhoisJSON API. Free WHOIS lookup tool.',
    category: 'network',
    tags: ['whois', 'domain', 'registration', 'owner', 'registrar'],
    keywords: ['WHOIS lookup', 'domain WHOIS', 'domain registration info', 'WHOIS search', 'domain owner lookup'],
    icon: 'FileText',
    relatedTools: ['address-lookup', 'dns-lookup'],
    phase: 3,
  },
  {
    slug: 'website-status-checker',
    name: 'Website Status Checker',
    shortDescription: 'Monitor website uptime and availability',
    description: 'Check if a website is online or down. Monitor uptime, response time, and status codes using UpDown.io API. Free website monitoring.',
    category: 'network',
    tags: ['website', 'status', 'uptime', 'monitor', 'availability', 'down'],
    keywords: ['website status checker', 'website uptime', 'is website down', 'site status', 'uptime monitor', 'website availability'],
    icon: 'Activity',
    relatedTools: ['internet-speed-test', 'ssl-certificate-checker'],
    phase: 3,
  },
  {
    slug: 'url-redirect-tracer',
    name: 'URL Redirect Tracer',
    shortDescription: 'Follow and analyze HTTP redirect chains',
    description: 'Trace the full redirect chain for any URL. See all 301, 302, and other redirects with status codes and headers. Free redirect checker.',
    category: 'network',
    tags: ['url', 'redirect', 'tracer', 'chain', '301', '302'],
    keywords: ['URL redirect tracer', 'redirect checker', 'follow redirects', 'HTTP redirect chain', 'URL tracer', '301 redirect'],
    icon: 'ArrowRight',
    relatedTools: ['http-headers-checker', 'website-status-checker'],
    phase: 3,
  },

  // ── Creative Tools ─────────────────────────────────────────────────────────────

  {
    slug: 'ascii-art-generator',
    name: 'ASCII Art Generator',
    shortDescription: 'Convert images to ASCII text art',
    description: 'Convert images to ASCII art text instantly. Upload JPG, PNG, or GIF and create stunning text-based artwork. Free, no sign-up required.',
    category: 'creative',
    tags: ['ascii', 'art', 'text', 'image', 'convert', 'generator'],
    keywords: ['ascii art generator', 'image to ascii', 'text art generator', 'ascii converter', 'picture to text art'],
    icon: 'Type',
    relatedTools: ['meme-generator', 'filter-effect-studio'],
    phase: 3,
  },
  {
    slug: 'meme-generator',
    name: 'Meme Generator',
    shortDescription: 'Create custom memes with text',
    description: 'Create custom memes instantly with our free meme generator. Add text to images, choose fonts, and download your memes. No sign-up required.',
    category: 'creative',
    tags: ['meme', 'generator', 'text', 'image', 'create', 'fun'],
    keywords: ['meme generator', 'make a meme', 'create meme online', 'meme maker', 'text on image'],
    icon: 'Smile',
    relatedTools: ['ascii-art-generator', 'meme-sticker-studio'],
    phase: 3,
  },
  {
    slug: 'meme-sticker-studio',
    name: 'Meme & Sticker Studio',
    shortDescription: 'Advanced meme & sticker editor with layers',
    description: 'Create custom memes and stickers with our advanced studio. Add text, stickers, effects, and layers. Download in multiple formats. Free, no sign-up required.',
    category: 'creative',
    tags: ['meme', 'sticker', 'editor', 'layers', 'effects', 'creative'],
    keywords: ['meme and sticker studio', 'create stickers online', 'sticker maker', 'meme creator', 'image editor'],
    icon: 'Layers',
    relatedTools: ['meme-generator', 'filter-effect-studio'],
    phase: 3,
  },
  {
    slug: 'optical-illusion-lab',
    name: 'Optical Illusion Lab',
    shortDescription: 'Create mind-bending optical illusions',
    description: 'Create stunning optical illusions and visual effects online. Generate spiral patterns, moiré effects, and more. Free, no sign-up required.',
    category: 'creative',
    tags: ['optical', 'illusion', 'visual', 'effects', 'spiral', 'pattern'],
    keywords: ['optical illusion generator', 'create optical illusions', 'visual effects generator', 'spiral pattern maker', 'moire effect'],
    icon: 'Eye',
    relatedTools: ['filter-effect-studio'],
    phase: 3,
  },
  {
    slug: 'filter-effect-studio',
    name: 'Filter & Effect Studio',
    shortDescription: 'Apply professional filters and effects to images',
    description: 'Apply professional filters and effects to your images online. Vintage, blur, sharpen, color adjustments and more. Free, no sign-up required.',
    category: 'creative',
    tags: ['filter', 'effect', 'image', 'editor', 'vintage', 'blur'],
    keywords: ['image filter studio', 'apply image filters', 'photo effects', 'image editor online', 'filter effects'],
    icon: 'Wand2',
    relatedTools: ['meme-sticker-studio', 'optical-illusion-lab'],
    phase: 3,
  },
  
  // ── Phase 4: Financial Calculators ──────────────────────────────────────────
  {
    slug: 'loan-calculator',
    name: 'Loan Calculator',
    shortDescription: 'Calculate monthly payments, interest & total cost',
    description: 'Calculate loan payments, total interest, and total cost with our free loan calculator. Works for mortgages, auto loans, personal loans, and more.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['loan', 'mortgage', 'payment', 'interest', 'calculator', 'finance'],
    keywords: ['loan calculator', 'monthly payment calculator', 'loan interest calculator', 'mortgage calculator', 'auto loan calculator'],
    icon: 'Calculator',
    phase: 4,
  },
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    shortDescription: 'Calculate Equated Monthly Installment',
    description: 'Calculate your EMI (Equated Monthly Installment) for home loans, car loans, personal loans, and more. Free EMI calculator with detailed payment schedule.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['emi', 'loan', 'payment', 'calculator', 'finance', 'india'],
    keywords: ['EMI calculator', 'equated monthly installment', 'loan EMI calculator', 'home loan EMI', 'car loan EMI'],
    icon: 'Calculator',
    phase: 4,
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    shortDescription: 'Calculate growth with compound interest',
    description: 'Calculate compound interest on investments and savings with our free calculator. See how your money grows over time with different compounding frequencies.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['compound', 'interest', 'investment', 'savings', 'calculator', 'growth'],
    keywords: ['compound interest calculator', 'investment growth calculator', 'savings compound interest', 'compound interest formula', 'investment calculator'],
    icon: 'TrendingUp',
    phase: 4,
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    shortDescription: 'Calculate simple interest using I = PRT',
    description: 'Calculate simple interest on loans and investments using the I = PRT formula. Free calculator with detailed breakdown of principal, rate, and time.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['simple', 'interest', 'loan', 'investment', 'calculator', 'prt'],
    keywords: ['simple interest calculator', 'simple interest formula', 'loan interest calculator', 'basic interest calculation', 'PRT formula'],
    icon: 'Calculator',
    phase: 4,
  },
  {
    slug: 'savings-calculator',
    name: 'Savings Calculator',
    shortDescription: 'Future value with regular deposits',
    description: 'Calculate your savings growth with regular deposits. See how much you\'ll save over time with our free savings calculator featuring compound interest.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['savings', 'future', 'value', 'deposit', 'calculator', 'growth'],
    keywords: ['savings calculator', 'savings growth calculator', 'future value calculator', 'regular deposit savings', 'compound interest savings'],
    icon: 'PiggyBank',
    phase: 4,
  },
  {
    slug: 'investment-calculator',
    name: 'Investment Calculator',
    shortDescription: 'ROI & growth projections',
    description: 'Calculate investment returns, ROI, and growth projections with our free investment calculator. Plan your portfolio growth with compound interest analysis.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['investment', 'ROI', 'growth', 'portfolio', 'calculator', 'return'],
    keywords: ['investment calculator', 'ROI calculator', 'investment growth calculator', 'portfolio return calculator', 'compound interest investment'],
    icon: 'TrendingUp',
    phase: 4,
  },
  {
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    shortDescription: 'Calculate Return on Investment',
    description: 'Calculate ROI (Return on Investment) instantly with our free calculator. Simple formula to measure investment profitability and compare returns.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['ROI', 'return', 'investment', 'profitability', 'calculator', 'finance'],
    keywords: ['ROI calculator', 'return on investment calculator', 'investment profitability', 'ROI formula', 'investment return calculator'],
    icon: 'TrendingUp',
    phase: 4,
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    shortDescription: 'Calculate % off sale price',
    description: 'Calculate discount amounts and final sale prices instantly. Free discount calculator for shopping, sales, and percentage off calculations.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['discount', 'sale', 'price', 'calculator', 'shopping', 'percent'],
    keywords: ['discount calculator', 'percent off calculator', 'sale price calculator', 'discount percentage calculator', 'shopping calculator'],
    icon: 'Tag',
    phase: 4,
  },
  {
    slug: 'percent-off-calculator',
    name: 'Percent Off Calculator',
    shortDescription: 'Calculate percentage discounts',
    description: 'Calculate sale prices and discount percentages instantly. Free percent off calculator for shopping with multiple item support.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['percent', 'discount', 'sale', 'price', 'calculator', 'shopping'],
    keywords: ['percent off calculator', 'discount calculator', 'sale price calculator', 'percentage discount', 'shopping calculator'],
    icon: 'Percent',
    phase: 4,
  },
  {
    slug: 'sales-tax-calculator',
    name: 'Sales Tax Calculator',
    shortDescription: 'Calculate sales tax on purchases',
    description: 'Calculate sales tax on purchases with our free calculator. Determine total cost including tax for any purchase amount.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['sales', 'tax', 'calculator', 'purchase', 'price', 'finance'],
    keywords: ['sales tax calculator', 'tax calculator', 'purchase tax calculator', 'calculate sales tax', 'sales tax computation'],
    icon: 'Receipt',
    phase: 4,
  },
  {
    slug: 'vat-calculator',
    name: 'VAT Calculator',
    shortDescription: 'Add or remove VAT from prices',
    description: 'Calculate VAT (Value Added Tax) on prices with our free calculator. Add or remove VAT from any price instantly.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['VAT', 'tax', 'calculator', 'price', 'finance', 'eu'],
    keywords: ['VAT calculator', 'value added tax calculator', 'add VAT', 'remove VAT', 'tax calculator'],
    icon: 'FileText',
    phase: 4,
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    shortDescription: 'Calculate tips and split bills',
    description: 'Calculate tips and split bills between people with our free tip calculator. Perfect for restaurants and shared expenses.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['tip', 'bill', 'split', 'calculator', 'restaurant', 'share'],
    keywords: ['tip calculator', 'bill splitter', 'calculate tip', 'split bill calculator', 'restaurant tip calculator'],
    icon: 'DollarSign',
    phase: 4,
  },
  {
    slug: 'margin-calculator',
    name: 'Margin Calculator',
    shortDescription: 'Calculate profit margin and markup',
    description: 'Calculate profit margin and markup on products with our free margin calculator. Essential for pricing and profit analysis.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['margin', 'profit', 'markup', 'calculator', 'business', 'pricing'],
    keywords: ['margin calculator', 'profit margin calculator', 'markup calculator', 'business calculator', 'pricing calculator'],
    icon: 'TrendingUp',
    phase: 4,
  },
  {
    slug: 'commission-calculator',
    name: 'Commission Calculator',
    shortDescription: 'Calculate sales commission earnings',
    description: 'Calculate commission earnings from sales with our free commission calculator. Support for different commission structures and base salary.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['commission', 'sales', 'calculator', 'earnings', 'income', 'business'],
    keywords: ['commission calculator', 'sales commission calculator', 'calculate commission', 'sales earnings calculator', 'commission structure'],
    icon: 'DollarSign',
    phase: 4,
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    shortDescription: 'Convert salary between hourly, weekly, monthly, annual',
    description: 'Convert salary between different pay periods with our free salary calculator. Calculate hourly wage from annual salary and vice versa.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['salary', 'hourly', 'wage', 'calculator', 'income', 'conversion'],
    keywords: ['salary calculator', 'hourly wage calculator', 'annual salary calculator', 'salary conversion', 'wage calculator'],
    icon: 'DollarSign',
    phase: 4,
  },
  {
    slug: 'budget-calculator',
    name: 'Budget Calculator',
    shortDescription: '50/30/20 rule budget planning',
    description: 'Create a personal budget with the 50/30/20 rule. Calculate needs, wants, and savings allocations. Free budget calculator for financial planning.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['budget', 'finance', 'planning', 'calculator', '503020', 'rule'],
    keywords: ['budget calculator', '50/30/20 rule calculator', 'personal budget calculator', 'budget planning tool', 'monthly budget calculator'],
    icon: 'PieChart',
    phase: 4,
  },
  {
    slug: 'debt-payoff-calculator',
    name: 'Debt Payoff Calculator',
    shortDescription: 'Calculate debt payoff timeline',
    description: 'Calculate your debt payoff timeline with avalanche and snowball methods. Free debt payoff calculator with payment strategies and interest savings.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['debt', 'payoff', 'calculator', 'finance', 'avalanche', 'snowball'],
    keywords: ['debt payoff calculator', 'debt avalanche calculator', 'debt snowball calculator', 'debt payoff timeline', 'debt reduction calculator'],
    icon: 'TrendingDown',
    phase: 4,
  },
  {
    slug: 'credit-card-payoff-calculator',
    name: 'Credit Card Payoff Calculator',
    shortDescription: 'Calculate credit card payoff timeline',
    description: 'Calculate credit card payoff timeline and interest savings with our free calculator. See how long to pay off your credit card debt.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['credit', 'card', 'payoff', 'calculator', 'debt', 'finance'],
    keywords: ['credit card payoff calculator', 'credit card debt calculator', 'pay off credit card', 'credit card interest calculator', 'debt payoff'],
    icon: 'CreditCard',
    phase: 4,
  },
  {
    slug: 'student-loan-calculator',
    name: 'Student Loan Calculator',
    shortDescription: 'Calculate student loan repayment',
    description: 'Calculate student loan payments and repayment timeline with our free calculator. Support for different repayment plans and interest rates.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['student', 'loan', 'repayment', 'calculator', 'education', 'finance'],
    keywords: ['student loan calculator', 'student loan repayment calculator', 'education loan calculator', 'loan payment calculator', 'college loan calculator'],
    icon: 'GraduationCap',
    phase: 4,
  },
  {
    slug: 'present-value-calculator',
    name: 'Present Value Calculator',
    shortDescription: 'Calculate present value of future money',
    description: 'Calculate present value of future cash flows with our free calculator. Discount future amounts to today\'s value using time value of money.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['present', 'value', 'discount', 'calculator', 'finance', 'investment'],
    keywords: ['present value calculator', 'PV calculator', 'discount rate calculator', 'time value of money', 'investment valuation'],
    icon: 'Calculator',
    phase: 4,
  },
  {
    slug: 'future-value-calculator',
    name: 'Future Value Calculator',
    shortDescription: 'Calculate future value of investments',
    description: 'Calculate future value of investments with our free calculator. Project investment growth with compound interest and regular contributions.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['future', 'value', 'investment', 'calculator', 'growth', 'compound'],
    keywords: ['future value calculator', 'FV calculator', 'investment growth calculator', 'compound interest calculator', 'savings projection'],
    icon: 'TrendingUp',
    phase: 4,
  },
  {
    slug: 'break-even-calculator',
    name: 'Break-Even Calculator',
    shortDescription: 'Calculate business break-even point',
    description: 'Calculate break-even point for your business with our free calculator. Determine how many units you need to sell to cover costs.',
    category: 'calculator',
    subcategory: 'financial-calculators',
    tags: ['break-even', 'business', 'calculator', 'costs', 'profit', 'analysis'],
    keywords: ['break even calculator', 'break-even point calculator', 'business break-even analysis', 'profit calculation', 'cost analysis'],
    icon: 'Target',
    phase: 4,
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    shortDescription: 'Calculate body mass index (BMI)',
    description: "Calculate your Body Mass Index (BMI) using metric or imperial units to evaluate weight health. Free BMI calculator for adults.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["bmi","health","weight","body mass index","fitness"],
    keywords: ["BMI calculator","body mass index calculator","calculate BMI","metric BMI","imperial BMI"],
    icon: 'Activity',
    phase: 4,
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    shortDescription: 'Calculate Basal Metabolic Rate (BMR)',
    description: "Calculate your Basal Metabolic Rate (BMR) using Mifflin-St Jeor equation. Free BMR calculator for daily calorie needs.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["bmr","health","fitness","calories","metabolic rate"],
    keywords: ["BMR calculator","basal metabolic rate","Mifflin-St Jeor","calories BMR"],
    icon: 'Flame',
    phase: 4,
  },
  {
    slug: 'tdee-calculator',
    name: 'TDEE Calculator',
    shortDescription: 'Calculate daily energy expenditure',
    description: "Calculate your Total Daily Energy Expenditure (TDEE) based on your activity level. Free TDEE calculator for weight management.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["tdee","calories","metabolism","fitness","bmr"],
    keywords: ["TDEE calculator","total daily energy expenditure","calculate TDEE","metabolic rate calculator"],
    icon: 'Flame',
    phase: 4,
  },
  {
    slug: 'calorie-calculator',
    name: 'Calorie Calculator',
    shortDescription: 'Calculate goal-based daily intake',
    description: "Calculate target daily calorie intake for weight loss, maintenance, or weight gain goals. Free calorie calculator for diet planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["calories","weight loss","calorie deficit","weight gain","diet"],
    keywords: ["calorie calculator","daily calorie intake","diet calculator","weight loss calories"],
    icon: 'Apple',
    phase: 4,
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    shortDescription: 'Calculate ideal weight range',
    description: "Estimate your ideal body weight using Devine, Robinson, Miller, and Hamwi methods. Free ideal weight calculator for health goals.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["ideal weight","weight","health","body weight","formulas"],
    keywords: ["ideal weight calculator","calculate ideal weight","Devine formula","Robinson formula"],
    icon: 'Scale',
    phase: 4,
  },
  {
    slug: 'body-fat-calculator',
    name: 'Body Fat Calculator',
    shortDescription: 'Calculate body fat percentage',
    description: "Calculate body fat percentage using the US Navy Circumference Method. Free body fat calculator for fitness tracking.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["body fat","fitness","weight","health","US Navy method"],
    keywords: ["body fat calculator","US Navy body fat","calculate body fat","waist measurement"],
    icon: 'Percent',
    phase: 4,
  },
  {
    slug: 'lean-body-mass-calculator',
    name: 'Lean Body Mass Calculator',
    shortDescription: 'Calculate lean body mass (LBM)',
    description: "Calculate lean body mass (LBM) using total body weight and body fat percentage. Free LBM calculator for body composition analysis.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["lbm","lean body mass","fitness","body composition","muscle"],
    keywords: ["lean body mass calculator","calculate LBM","lean muscle weight"],
    icon: 'Dumbbell',
    phase: 4,
  },
  {
    slug: 'protein-calculator',
    name: 'Protein Calculator',
    shortDescription: 'Calculate daily protein requirements',
    description: "Calculate daily protein requirements based on body weight, activity level, and fitness goals. Free protein calculator for nutrition planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["protein","diet","macros","nutrition","muscle"],
    keywords: ["protein calculator","daily protein requirement","calculate protein intake"],
    icon: 'Dumbbell',
    phase: 4,
  },
  {
    slug: 'macro-calculator',
    name: 'Macro Calculator',
    shortDescription: 'Calculate macronutrient splits',
    description: "Calculate daily macronutrient distribution based on calorie targets and dietary preferences. Free macro calculator for balanced diet planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["macros","calories","nutrition","protein","diet"],
    keywords: ["macro calculator","calculate macros","carb protein fat split","keto macros"],
    icon: 'PieChart',
    phase: 4,
  },
  {
    slug: 'target-heart-rate-calculator',
    name: 'Target Heart Rate Calculator',
    shortDescription: 'Calculate training heart rate zones',
    description: "Calculate target and maximum heart rates for exercise using standard age formulas. Free heart rate calculator for workout optimization.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["heart rate","cardio","fitness","zones","exercise"],
    keywords: ["target heart rate calculator","maximum heart rate","exercise zones","karvonen method"],
    icon: 'Activity',
    phase: 4,
  },
  {
    slug: 'one-rep-max-calculator',
    name: 'One Rep Max Calculator',
    shortDescription: 'Calculate lift strength estimates',
    description: "Estimate your lifting one-rep max (1RM) using Epley and Brzycki equations. Free 1RM calculator for strength training planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["strength","1rm","powerlifting","weightlifting","gym"],
    keywords: ["one rep max calculator","1RM calculator","strength calculation","gym formulas"],
    icon: 'Dumbbell',
    phase: 4,
  },
  {
    slug: 'pace-calculator',
    name: 'Pace Calculator',
    shortDescription: 'Calculate running pace or distance',
    description: "Calculate average running or walking pace, time elapsed, or target distance. Free pace calculator for runners and athletes.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["running","pace","cardio","splits","fitness"],
    keywords: ["pace calculator","running pace","split times","marathon calculator"],
    icon: 'Activity',
    phase: 4,
  },
  {
    slug: 'calories-burned-calculator',
    name: 'Calories Burned Calculator',
    shortDescription: 'Calculate calorie burn from exercise',
    description: "Estimate calories burned during fitness activities using Metabolic Equivalent of Task (MET) levels.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["calories burned","exercise","cardio","weight loss","burn rate"],
    keywords: ["calories burned calculator","MET index","activity calorie burner","calculate burn"],
    icon: 'Flame',
    phase: 4,
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    shortDescription: 'Calculate hydration needs',
    description: "Calculate recommended daily water intake volume based on body weight and activity durations. Free hydration calculator for wellness.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["water","hydration","health","daily goal","fitness"],
    keywords: ["water intake calculator","daily water intake","calculate hydration"],
    icon: 'Droplet',
    phase: 4,
  },
  {
    slug: 'sleep-calculator',
    name: 'Sleep Calculator',
    shortDescription: 'Calculate optimal sleep schedules',
    description: "Plan sleep schedules and wake-up times based on 90-minute sleep cycles. Free sleep calculator for better rest and energy.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["sleep","rest","health","sleep cycles","circadian rhythm"],
    keywords: ["sleep calculator","sleep cycle planner","wake up times","bedtime planner"],
    icon: 'Moon',
    phase: 4,
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    shortDescription: 'Calculate exact calendar age',
    description: "Calculate age in exact years, months, and days from a birthdate. Free age calculator for precise date calculations.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["age","date difference","time","chronological age","birthday"],
    keywords: ["age calculator","calculate age","date delta","age in days"],
    icon: 'Calendar',
    phase: 4,
  },
  {
    slug: 'due-date-calculator',
    name: 'Due Date Calculator',
    shortDescription: 'Estimate pregnancy due date',
    description: "Calculate pregnancy due date and gestational progress indicator using Naegele's rule. Free due date calculator for expectant parents.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["due date","pregnancy","baby","maternity","calendar"],
    keywords: ["due date calculator","pregnancy calculator","Naegele rule due date"],
    icon: 'Baby',
    phase: 4,
  },
  {
    slug: 'ovulation-calculator',
    name: 'Ovulation Calculator',
    shortDescription: 'Calculate fertile windows',
    description: "Estimate ovulation dates and fertile windows based on menstrual cycle lengths. Free ovulation calculator for family planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["ovulation","fertility","menstrual","conception","pregnancy"],
    keywords: ["ovulation calculator","fertility window","menstrual cycle calculator"],
    icon: 'Calendar',
    phase: 4,
  },
  {
    slug: 'period-calculator',
    name: 'Period Calculator',
    shortDescription: 'Predict next menstruation dates',
    description: "Predict upcoming period cycle start dates based on history variables. Free period calculator for menstrual cycle tracking.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["period","menstruation","women health","cycle tracker","ovulation"],
    keywords: ["period calculator","period predictor","menstruation cycles"],
    icon: 'Calendar',
    phase: 4,
  },
  {
    slug: 'bac-calculator',
    name: 'BAC Calculator',
    shortDescription: 'Calculate Blood Alcohol Concentration',
    description: "Estimate Blood Alcohol Concentration (BAC) using the Widmark formula. Free BAC calculator for responsible drinking awareness.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["bac","blood alcohol","sober","widmark","alcohol limit"],
    keywords: ["BAC calculator","calculate BAC","Widmark formula","alcohol rate"],
    icon: 'Activity',
    phase: 4,
  },
  {
    slug: 'body-surface-area-calculator',
    name: 'Body Surface Area Calculator',
    shortDescription: 'Calculate Body Surface Area (BSA)',
    description: "Calculate your body surface area (BSA) using DuBois or Mosteller formulas. Free BSA calculator for medical dosage calculations.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["bsa","body surface","medical","height","weight"],
    keywords: ["BSA calculator","body surface area","DuBois formula","Mosteller formula"],
    icon: 'Activity',
    phase: 4,
  },
  {
    slug: 'fat-intake-calculator',
    name: 'Fat Intake Calculator',
    shortDescription: 'Calculate calorie-based fat limits',
    description: "Calculate recommended daily total fat and saturated fat limits matching calorie goals. Free fat intake calculator for healthy diet planning.",
    category: 'calculator',
    subcategory: 'health-fitness-calculators',
    tags: ["fat limits","nutrition","diet","saturated fat","calories"],
    keywords: ["fat intake calculator","daily fat limit","saturated fat calculation","fat grams"],
    icon: 'Apple',
    phase: 4,
  },
];

// ── Helpers ──────────────────────────────────────────────────────────

export const CATEGORIES: { value: ToolCategory; label: string; icon: string; description: string }[] = [
  { value: 'image', label: 'Image Tools', icon: 'Image', description: 'Compress, resize, crop, convert, and optimize images directly in your browser. Perfect for web developers, designers, and content creators.' },
  { value: 'text', label: 'Text Tools', icon: 'Type', description: 'Count words, analyze text, generate placeholder content, and format text with our comprehensive text processing tools.' },
  { value: 'developer', label: 'Developer Tools', icon: 'Code2', description: 'Format, validate, convert, and debug code with our developer utilities. JSON, Base64, URL encoding, regex testing, and more.' },
  { value: 'converter', label: 'Converters', icon: 'ArrowLeftRight', description: 'Convert between different units, formats, and data types. Length, weight, temperature, and file format converters.' },
  { value: 'generator', label: 'Generators', icon: 'Wand2', description: 'Generate QR codes, passwords, UUIDs, Lorem Ipsum text, and other content instantly. Perfect for developers and designers.' },
  { value: 'calculator', label: 'Calculators', icon: 'Calculator', description: 'Financial, health & fitness, math, and science calculators. Calculate loans, BMI, equations, and more in your browser.' },
  { value: 'security', label: 'Security', icon: 'Shield', description: 'Generate secure passwords, cryptographic hashes, and protect your data with our privacy-focused security tools.' },
  { value: 'seo', label: 'SEO Tools', icon: 'Search', description: 'Optimize your website for search engines with meta tag generators, keyword analysis, SERP previews, and SEO auditing tools.' },
  { value: 'network', label: 'Network Tools', icon: 'Globe', description: 'Test internet speed, lookup IP addresses, query DNS records, and analyze network performance with our network utilities.' },
  { value: 'creative', label: 'Creative Tools', icon: 'Palette', description: 'Extract color palettes, generate creative content, and design with our creative tools for designers and artists.' },
];

// Calculator subcategories
export const CALCULATOR_SUBCATEGORIES: { value: string; label: string; icon: string }[] = [
  { value: 'financial-calculators', label: 'Financial Calculators', icon: 'DollarSign' },
  { value: 'health-fitness-calculators', label: 'Health & Fitness Calculators', icon: 'Heart' },
  { value: 'math-calculators', label: 'Math Calculators', icon: 'Calculator' },
  { value: 'science-calculators', label: 'Science Calculators', icon: 'Flask' },
];

export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getRelatedTools(slug: string): Tool[] {
  const tool = getTool(slug);
  if (!tool?.relatedTools) return [];
  return tool.relatedTools
    .map((s) => getTool(s))
    .filter((t): t is Tool => t !== undefined);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.shortDescription.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q))
  );
}
