// src/lib/constants/tools.ts
// Central registry of all tools — drives routing, SEO, and UI

export type ToolCategory =
  | 'image'
  | 'text'
  | 'developer'
  | 'converter'
  | 'generator'
  | 'calculator'
  | 'security'
  | 'seo'
  | 'network';

export interface Tool {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  category: ToolCategory;
  tags: string[];
  keywords: string[];
  icon: string;
  isNew?: boolean;
  isPopular?: boolean;
  relatedTools?: string[];
  phase: 1 | 2 | 3 | 4; // which phase this tool ships in
}

export const TOOLS: Tool[] = [
  // ── Phase 2: Core Tools ──────────────────────────────────────────

  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress JPG, PNG, WebP without losing quality',
    description:
      'Compress and optimize images online for free. Reduce JPG, PNG, and WebP file sizes without losing quality. No upload required — works in your browser.',
    category: 'image',
    tags: ['compress', 'optimize', 'jpg', 'png', 'webp', 'image', 'reduce'],
    keywords: ['compress image online free', 'reduce image size', 'image optimizer'],
    icon: 'ImageDown',
    isPopular: true,
    relatedTools: ['image-resizer', 'image-converter', 'image-cropper'],
    phase: 2,
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    shortDescription: 'Create QR codes for URLs, text, WiFi, and more',
    description:
      'Generate QR codes for URLs, text, email, phone, and WiFi for free. Download as PNG or SVG. No sign-up required.',
    category: 'generator',
    tags: ['qr', 'qrcode', 'barcode', 'generate', 'url', 'wifi'],
    keywords: ['free QR code generator', 'create QR code online', 'QR code maker'],
    icon: 'QrCode',
    isPopular: true,
    relatedTools: ['barcode-generator', 'password-generator'],
    phase: 2,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Generate strong, random, secure passwords',
    description:
      'Generate strong, random, secure passwords instantly. Customize length, symbols, numbers, and more. Free online password generator.',
    category: 'security',
    tags: ['password', 'security', 'random', 'secure', 'generate'],
    keywords: ['strong password generator', 'random password generator', 'secure password'],
    icon: 'KeyRound',
    isPopular: true,
    relatedTools: ['hash-generator', 'uuid-generator'],
    phase: 2,
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    shortDescription: 'Crop and resize images with custom aspect ratios',
    description:
      'Crop and resize images online for free. Supports custom ratios, square, 16:9, and more. Download cropped image instantly.',
    category: 'image',
    tags: ['crop', 'resize', 'cut', 'image', 'aspect ratio'],
    keywords: ['crop image online free', 'image crop tool', 'cut image online'],
    icon: 'Crop',
    relatedTools: ['image-compressor', 'image-resizer', 'image-converter'],
    phase: 2,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription: 'Format, validate, and beautify JSON online',
    description:
      'Format, beautify, and validate JSON online for free. Minify JSON, fix errors, and view JSON tree structure. No sign-up required.',
    category: 'developer',
    tags: ['json', 'format', 'validate', 'beautify', 'minify', 'developer'],
    keywords: ['JSON formatter online', 'JSON beautifier', 'validate JSON', 'format JSON'],
    icon: 'Braces',
    isPopular: true,
    relatedTools: ['base64-encoder', 'url-encoder', 'hash-generator'],
    phase: 2,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, sentences in real time',
    description:
      'Count words, characters, sentences, and paragraphs in real time. Free online word counter for writers, students, and bloggers.',
    category: 'text',
    tags: ['word', 'character', 'count', 'text', 'writer', 'sentence'],
    keywords: ['word counter online', 'character count', 'word count tool'],
    icon: 'AlignLeft',
    relatedTools: ['lorem-ipsum', 'case-converter', 'markdown-previewer'],
    phase: 2,
  },
  {
    slug: 'color-palette',
    name: 'Color Palette Extractor',
    shortDescription: 'Extract dominant colors from any image',
    description:
      'Upload an image and instantly extract its dominant color palette. Get HEX, RGB, and HSL codes. Free, no sign-up required.',
    category: 'image',
    tags: ['color', 'palette', 'extract', 'image', 'hex', 'rgb'],
    keywords: ['color palette from image', 'extract colors from image', 'dominant colors'],
    icon: 'Palette',
    relatedTools: ['image-compressor', 'image-cropper', 'color-picker'],
    phase: 2,
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder / Decoder',
    shortDescription: 'Encode and decode text, files, and images to Base64',
    description:
      'Encode text or files to Base64 and decode Base64 strings online for free. Supports text, images, and files.',
    category: 'developer',
    tags: ['base64', 'encode', 'decode', 'developer', 'convert'],
    keywords: ['base64 encode online', 'base64 decoder', 'text to base64'],
    icon: 'Binary',
    relatedTools: ['url-encoder', 'hash-generator', 'json-formatter'],
    phase: 2,
  },

  // ── Phase 3: Extended Tools ───────────────────────────────────────

  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to any width and height online for free',
    description: 'Resize images to any width and height online for free. Maintain aspect ratio or set custom dimensions. Download resized images instantly.',
    category: 'image',
    tags: ['resize', 'image', 'dimension', 'scale', 'width', 'height'],
    keywords: ['resize image online free', 'change image size', 'image dimensions', 'resize photo', 'scale image'],
    icon: 'Maximize',
    relatedTools: ['image-compressor', 'image-cropper'],
    phase: 3,
  },
  {
    slug: 'image-metadata-remover',
    name: 'Image Metadata Remover',
    shortDescription: 'Remove EXIF metadata and GPS data from images',
    description: 'Remove EXIF metadata, GPS location, and hidden data from images online for free. Protect your privacy by stripping image metadata directly in your browser.',
    category: 'image',
    tags: ['metadata', 'exif', 'gps', 'privacy', 'remove', 'clean'],
    keywords: ['remove image metadata online free', 'remove exif data', 'strip image metadata', 'clean image info', 'remove gps from photos'],
    icon: 'ShieldCheck',
    relatedTools: ['image-compressor', 'image-resizer'],
    phase: 3,
  },
  {
    slug: 'image-batch-resizer',
    name: 'Image Batch Resizer',
    shortDescription: 'Resize multiple images at once online for free',
    description: 'Resize multiple images at once online for free. Batch resize JPG, PNG, WebP files with custom dimensions, percentage scaling, or presets. Download as ZIP.',
    category: 'image',
    tags: ['batch', 'resize', 'multiple', 'bulk', 'image'],
    keywords: ['batch resize images online free', 'resize multiple images', 'bulk image resizer', 'batch image resize', 'resize photos in bulk'],
    icon: 'Layers',
    relatedTools: ['image-resizer', 'image-compressor'],
    phase: 3,
  },
  {
    slug: 'image-converter',
    name: 'Image Format Converter',
    shortDescription: 'Convert between JPG, PNG, WebP, GIF formats',
    description: 'Convert images between JPG, PNG, WebP, and GIF formats online for free. Fast browser-based conversion.',
    category: 'image',
    tags: ['convert', 'format', 'jpg', 'png', 'webp', 'image'],
    keywords: ['image format converter', 'convert png to jpg', 'webp converter'],
    icon: 'RefreshCw',
    relatedTools: ['image-compressor', 'image-resizer'],
    phase: 3,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    shortDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 cryptographic hashes online for free. Instant hash generation with no data sent to server.',
    category: 'security',
    tags: ['hash', 'md5', 'sha256', 'sha1', 'sha512', 'crypto', 'security'],
    keywords: ['hash generator online', 'MD5 hash', 'SHA-256 generator', 'SHA-1 hash', 'cryptographic hash'],
    icon: 'Hash',
    relatedTools: ['password-generator', 'base64-encoder'],
    phase: 3,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder / Decoder',
    shortDescription: 'Encode and decode URL strings',
    description: 'Encode and decode URL strings and query parameters online for free.',
    category: 'developer',
    tags: ['url', 'encode', 'decode', 'percent', 'developer'],
    keywords: ['URL encoder online', 'URL decoder', 'percent encode'],
    icon: 'Link',
    relatedTools: ['base64-encoder', 'json-formatter'],
    phase: 3,
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    shortDescription: 'Convert length, weight, temperature, and more',
    description: 'Convert between units of length, weight, temperature, area, speed, and more. Free online unit converter.',
    category: 'converter',
    tags: ['unit', 'convert', 'length', 'weight', 'temperature'],
    keywords: ['unit converter online', 'length converter', 'weight converter'],
    icon: 'ArrowLeftRight',
    relatedTools: [],
    phase: 3,
  },
  {
    slug: 'markdown-previewer',
    name: 'Markdown Previewer',
    shortDescription: 'Write and preview Markdown in real time',
    description: 'Write Markdown and see a live preview side by side. Supports GitHub Flavored Markdown.',
    category: 'text',
    tags: ['markdown', 'preview', 'text', 'editor', 'github'],
    keywords: ['markdown previewer online', 'markdown editor', 'live markdown preview'],
    icon: 'FileText',
    relatedTools: ['word-counter', 'lorem-ipsum'],
    phase: 3,
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate placeholder text for designs',
    description: 'Generate Lorem Ipsum placeholder text instantly. Choose words, sentences, or paragraphs. Perfect for designs and mockups.',
    category: 'generator',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'filler'],
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator', 'lorem ipsum text', 'filler text'],
    icon: 'Type',
    relatedTools: ['word-counter', 'markdown-previewer'],
    phase: 3,
  },

  // ── Phase 3: Developer Tools (Extended) ───────────────────────────────

  {
    slug: 'json-to-csv',
    name: 'JSON to CSV Converter',
    shortDescription: 'Convert JSON data to CSV format',
    description: 'Convert JSON arrays and objects to CSV format online for free. Download converted CSV files instantly.',
    category: 'developer',
    tags: ['json', 'csv', 'convert', 'export', 'data'],
    keywords: ['json to csv converter', 'convert json to csv', 'json csv export'],
    icon: 'FileSpreadsheet',
    relatedTools: ['json-formatter', 'json-diff'],
    phase: 3,
  },
  {
    slug: 'json-diff',
    name: 'JSON Diff Comparator',
    shortDescription: 'Compare two JSON files and find differences',
    description: 'Compare two JSON objects and visualize differences. Highlight added, removed, and modified fields.',
    category: 'developer',
    tags: ['json', 'diff', 'compare', 'difference', 'change'],
    keywords: ['json diff', 'compare json', 'json difference checker'],
    icon: 'GitCompare',
    relatedTools: ['json-formatter', 'json-to-csv'],
    phase: 3,
  },
  {
    slug: 'json-path-finder',
    name: 'JSON Path Finder',
    shortDescription: 'Find and extract values from JSON using JSONPath',
    description: 'Query JSON data using JSONPath expressions. Extract specific values and paths from complex JSON structures.',
    category: 'developer',
    tags: ['json', 'path', 'query', 'extract', 'jsonpath'],
    keywords: ['json path finder', 'jsonpath query', 'extract json values'],
    icon: 'Search',
    relatedTools: ['json-formatter', 'json-filter'],
    phase: 3,
  },
  {
    slug: 'json-escape',
    name: 'JSON Escape / Unescape',
    shortDescription: 'Escape and unescape JSON strings',
    description: 'Escape special characters in JSON strings and unescape escaped JSON. Handle quotes, backslashes, and Unicode.',
    category: 'developer',
    tags: ['json', 'escape', 'unescape', 'string', 'special characters'],
    keywords: ['json escape', 'json unescape', 'escape json string'],
    icon: 'Quote',
    relatedTools: ['json-formatter', 'json-stringify'],
    phase: 3,
  },
  {
    slug: 'json-stringify',
    name: 'JSON Stringify Tool',
    shortDescription: 'Convert JavaScript objects to JSON strings',
    description: 'Convert JavaScript objects to JSON strings with customizable spacing and formatting. Handle circular references.',
    category: 'developer',
    tags: ['json', 'stringify', 'object', 'convert', 'javascript'],
    keywords: ['json stringify', 'object to json', 'javascript to json'],
    icon: 'Braces',
    relatedTools: ['json-formatter', 'json-parse'],
    phase: 3,
  },
  {
    slug: 'json-parse',
    name: 'JSON Parse Tool',
    shortDescription: 'Parse JSON strings into JavaScript objects',
    description: 'Parse JSON strings into readable JavaScript objects. Validate JSON syntax and view parsed structure.',
    category: 'developer',
    tags: ['json', 'parse', 'validate', 'object', 'syntax'],
    keywords: ['json parse', 'parse json string', 'json validator'],
    icon: 'Code2',
    relatedTools: ['json-formatter', 'json-stringify'],
    phase: 3,
  },
  {
    slug: 'json-filter',
    name: 'JSON Filter Tool',
    shortDescription: 'Filter JSON data by keys and values',
    description: 'Filter JSON arrays and objects by keys, values, or custom conditions. Extract specific data from large JSON.',
    category: 'developer',
    tags: ['json', 'filter', 'query', 'extract', 'search'],
    keywords: ['json filter', 'filter json data', 'query json'],
    icon: 'Filter',
    relatedTools: ['json-formatter', 'json-path-finder'],
    phase: 3,
  },
  {
    slug: 'json-schema-visualizer',
    name: 'JSON Schema Visualizer',
    shortDescription: 'Visualize JSON Schema structure and validation',
    description: 'Visualize JSON Schema definitions and validate JSON against schemas. View schema structure in tree format.',
    category: 'developer',
    tags: ['json', 'schema', 'visualize', 'validate', 'structure'],
    keywords: ['json schema visualizer', 'json schema validator', 'view json schema'],
    icon: 'Network',
    relatedTools: ['json-formatter', 'json-parse'],
    phase: 3,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortDescription: 'Test regular expressions with real-time matching',
    description: 'Test regular expressions against text in real time. Highlight matches, capture groups, and replace patterns.',
    category: 'developer',
    tags: ['regex', 'regular expression', 'test', 'match', 'pattern'],
    keywords: ['regex tester', 'regular expression tester', 'test regex online'],
    icon: 'Regex',
    relatedTools: ['regex-explainer'],
    phase: 3,
  },
  {
    slug: 'regex-explainer',
    name: 'Regex Explainer',
    shortDescription: 'Explain regular expressions in plain English',
    description: 'Break down regular expressions and explain each part in plain English. Understand complex regex patterns.',
    category: 'developer',
    tags: ['regex', 'regular expression', 'explain', 'learn', 'documentation'],
    keywords: ['regex explainer', 'explain regex', 'regex documentation'],
    icon: 'BookOpen',
    relatedTools: ['regex-tester'],
    phase: 3,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortDescription: 'Generate UUID v4 and other UUID versions',
    description: 'Generate UUID v4, v1, and other versions. Create bulk UUIDs and copy to clipboard instantly.',
    category: 'developer',
    tags: ['uuid', 'guid', 'generate', 'identifier', 'unique'],
    keywords: ['uuid generator', 'generate uuid', 'uuid v4'],
    icon: 'Fingerprint',
    relatedTools: ['hash-generator', 'password-generator'],
    phase: 3,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    shortDescription: 'Decode and verify JSON Web Tokens',
    description: 'Decode JWT tokens to view header, payload, and signature. Verify token structure and expiration.',
    category: 'developer',
    tags: ['jwt', 'json web token', 'decode', 'verify', 'token'],
    keywords: ['jwt decoder', 'decode jwt', 'jwt token decoder'],
    icon: 'Lock',
    relatedTools: ['base64-encoder', 'hash-generator'],
    phase: 3,
  },
  {
    slug: 'string-converter',
    name: 'String Converter',
    shortDescription: 'Convert between string formats (camelCase, snake_case, etc.)',
    description: 'Convert string cases between camelCase, snake_case, kebab-case, PascalCase, and more.',
    category: 'developer',
    tags: ['string', 'convert', 'case', 'format', 'transform'],
    keywords: ['string converter', 'case converter', 'convert string case'],
    icon: 'TextCase',
    relatedTools: ['json-formatter', 'url-encoder'],
    phase: 3,
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format and beautify SQL queries',
    description: 'Format SQL queries with proper indentation and syntax highlighting. Support for MySQL, PostgreSQL, and more.',
    category: 'developer',
    tags: ['sql', 'format', 'beautify', 'query', 'database'],
    keywords: ['sql formatter', 'format sql', 'sql beautifier'],
    icon: 'Database',
    relatedTools: ['json-formatter', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortDescription: 'Convert Markdown to HTML',
    description: 'Convert Markdown text to HTML code. Supports GitHub Flavored Markdown and common syntax.',
    category: 'developer',
    tags: ['markdown', 'html', 'convert', 'markup', 'generate'],
    keywords: ['markdown to html', 'convert markdown', 'markdown html converter'],
    icon: 'FileCode',
    relatedTools: ['markdown-previewer', 'html-viewer'],
    phase: 3,
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    shortDescription: 'Compare two text blocks and find differences',
    description: 'Compare two text blocks and highlight differences. View added, removed, and modified lines side by side.',
    category: 'developer',
    tags: ['text', 'diff', 'compare', 'difference', 'change'],
    keywords: ['text diff', 'compare text', 'text difference checker'],
    icon: 'GitCompareArrows',
    relatedTools: ['json-diff', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'html-viewer',
    name: 'HTML Viewer & Live Preview',
    shortDescription: 'View and preview HTML code in real time',
    description: 'Write HTML code and see live preview instantly. Test HTML snippets and visualize rendered output.',
    category: 'developer',
    tags: ['html', 'preview', 'viewer', 'render', 'live'],
    keywords: ['html viewer', 'html preview', 'live html preview'],
    icon: 'Eye',
    relatedTools: ['markdown-to-html', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'code-minifier',
    name: 'Code Minifier',
    shortDescription: 'Minify JavaScript, CSS, and HTML code',
    description: 'Minify JavaScript, CSS, and HTML code to reduce file size. Remove whitespace and comments automatically.',
    category: 'developer',
    tags: ['code', 'minify', 'compress', 'optimize', 'reduce'],
    keywords: ['code minifier', 'minify javascript', 'minify css'],
    icon: 'Minimize2',
    relatedTools: ['json-formatter', 'sql-formatter'],
    phase: 3,
  },
  {
    slug: 'cron-builder',
    name: 'Cron Expression Builder',
    shortDescription: 'Build and test cron expressions visually',
    description: 'Build cron expressions with a visual interface. Test cron schedules and view next execution times.',
    category: 'developer',
    tags: ['cron', 'schedule', 'expression', 'builder', 'time'],
    keywords: ['cron builder', 'cron expression', 'cron schedule builder'],
    icon: 'Clock',
    relatedTools: ['uuid-generator'],
    phase: 3,
  },
  {
    slug: 'css-grid-generator',
    name: 'CSS Grid Generator',
    shortDescription: 'Generate CSS Grid layouts visually',
    description: 'Generate CSS Grid layouts with a visual builder. Configure columns, rows, gaps, and areas interactively.',
    category: 'developer',
    tags: ['css', 'grid', 'layout', 'generator', 'visual'],
    keywords: ['css grid generator', 'css grid layout', 'grid builder'],
    icon: 'Grid3x3',
    relatedTools: ['html-viewer', 'code-minifier'],
    phase: 3,
  },
  {
    slug: 'har-viewer',
    name: 'HAR Viewer',
    shortDescription: 'View and analyze HTTP Archive (HAR) files',
    description: 'Upload and analyze HAR files to view network requests, responses, timings, and headers.',
    category: 'developer',
    tags: ['har', 'http', 'archive', 'network', 'analyze'],
    keywords: ['har viewer', 'har file viewer', 'http archive viewer'],
    icon: 'FileJson',
    relatedTools: ['json-formatter', 'json-diff'],
    phase: 3,
  },
  {
    slug: 'security-header-analyzer',
    name: 'Security Header Analyzer',
    shortDescription: 'Analyze HTTP security headers',
    description: 'Analyze HTTP security headers like CSP, HSTS, X-Frame-Options. Get recommendations for improving security.',
    category: 'developer',
    tags: ['security', 'headers', 'http', 'analyze', 'csp'],
    keywords: ['security header analyzer', 'http security headers', 'csp analyzer'],
    icon: 'ShieldCheck',
    relatedTools: ['jwt-decoder', 'hash-generator'],
    phase: 3,
  },

  // ── SEO Tools ─────────────────────────────────────────────────────────────

  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    shortDescription: 'Generate SEO meta tags for your website',
    description: 'Generate meta tags for your website instantly. Create title, description, keywords, Open Graph, Twitter Card, and other SEO meta tags for free.',
    category: 'seo',
    tags: ['meta', 'tags', 'seo', 'open graph', 'twitter card'],
    keywords: ['meta tag generator', 'meta tags creator', 'SEO meta tags', 'HTML meta tags generator'],
    icon: 'Tag',
    relatedTools: ['open-graph-preview-generator', 'serp-snippet-preview'],
    phase: 3,
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    shortDescription: 'Analyze keyword usage in your content',
    description: 'Check keyword density in your content for free. Analyze word frequency, keyword repetition, and optimize your content for SEO.',
    category: 'seo',
    tags: ['keyword', 'density', 'seo', 'content', 'analysis'],
    keywords: ['keyword density checker', 'keyword analyzer', 'word frequency counter', 'SEO keyword analysis'],
    icon: 'BarChart3',
    relatedTools: ['readability-checker', 'title-description-length-checker'],
    phase: 3,
  },
  {
    slug: 'sitemap-generator',
    name: 'Sitemap Generator',
    shortDescription: 'Create XML sitemaps for search engines',
    description: 'Generate XML sitemaps for your website instantly. Add URLs, set priorities, change frequencies, and download valid sitemap files for free.',
    category: 'seo',
    tags: ['sitemap', 'xml', 'seo', 'search engine', 'indexing'],
    keywords: ['sitemap generator', 'XML sitemap creator', 'sitemap builder', 'Google sitemap generator'],
    icon: 'FileJson',
    relatedTools: ['robots-txt-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder (SEO)',
    shortDescription: 'Encode and decode URLs with SEO suggestions',
    description: 'Encode and decode URLs for SEO. Clean up URL parameters, fix special characters, and ensure your URLs are search engine friendly.',
    category: 'seo',
    tags: ['url', 'encode', 'decode', 'seo', 'clean'],
    keywords: ['URL encoder decoder SEO', 'URL cleaner', 'SEO URL tool', 'encode decode URL'],
    icon: 'Link',
    relatedTools: ['url-parameter-cleaner', 'sitemap-generator'],
    phase: 3,
  },
  {
    slug: 'open-graph-preview-generator',
    name: 'Open Graph Preview Generator',
    shortDescription: 'Test how your links appear on social media',
    description: 'Preview how your website appears on social media. Test Open Graph tags, see Facebook and LinkedIn previews, and optimize your social sharing.',
    category: 'seo',
    tags: ['open graph', 'og', 'social media', 'preview', 'facebook'],
    keywords: ['Open Graph preview generator', 'OG tag tester', 'social media preview', 'Facebook link preview'],
    icon: 'Eye',
    relatedTools: ['meta-tag-generator', 'open-graph-image-generator'],
    phase: 3,
  },
  {
    slug: 'open-graph-image-generator',
    name: 'Open Graph Image Generator',
    shortDescription: 'Create custom OG images for social sharing',
    description: 'Generate Open Graph images for social media sharing. Create custom OG images with your branding, text, and colors for free.',
    category: 'seo',
    tags: ['open graph', 'og', 'image', 'social media', 'generator'],
    keywords: ['Open Graph image generator', 'OG image creator', 'social media image generator', 'Facebook image maker'],
    icon: 'ImagePlus',
    relatedTools: ['open-graph-preview-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'serp-snippet-preview',
    name: 'SERP Snippet Preview',
    shortDescription: 'Preview Google search results appearance',
    description: 'Preview how your website appears in Google search results. Test title tags, meta descriptions, and optimize your SERP snippets for SEO.',
    category: 'seo',
    tags: ['serp', 'google', 'search', 'preview', 'snippet'],
    keywords: ['SERP snippet preview', 'Google search preview', 'SERP simulator', 'title tag preview'],
    icon: 'Search',
    relatedTools: ['title-description-length-checker', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'title-description-length-checker',
    name: 'Title & Description Length Checker',
    shortDescription: 'Check meta tag character limits for SEO',
    description: 'Check title tag and meta description length for SEO. Ensure your meta tags are within optimal character limits for Google and other search engines.',
    category: 'seo',
    tags: ['title', 'description', 'length', 'seo', 'meta'],
    keywords: ['title description length checker', 'meta tag length checker', 'SEO title analyzer', 'meta description counter'],
    icon: 'Ruler',
    relatedTools: ['serp-snippet-preview', 'keyword-density-checker'],
    phase: 3,
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    shortDescription: 'Create robots.txt files for crawler control',
    description: 'Generate robots.txt files for your website instantly. Control crawler access, set sitemap location, and manage SEO indexing for free.',
    category: 'seo',
    tags: ['robots', 'txt', 'crawler', 'seo', 'sitemap'],
    keywords: ['robots.txt generator', 'robots.txt creator', 'crawler control', 'SEO robots file'],
    icon: 'FileCode',
    relatedTools: ['sitemap-generator', 'meta-tag-generator'],
    phase: 3,
  },
  {
    slug: 'readability-checker',
    name: 'Readability Checker',
    shortDescription: 'Analyze text readability score',
    description: 'Check text readability score and analyze content quality. Calculate Flesch-Kincaid, Gunning Fog, and other readability metrics for SEO.',
    category: 'seo',
    tags: ['readability', 'text', 'seo', 'content', 'analysis'],
    keywords: ['readability checker', 'text readability analyzer', 'Flesch Kincaid score', 'content readability test'],
    icon: 'BookOpen',
    relatedTools: ['keyword-density-checker', 'title-description-length-checker'],
    phase: 3,
  },
  {
    slug: 'url-parameter-cleaner',
    name: 'URL Parameter Cleaner',
    shortDescription: 'Remove tracking parameters from URLs',
    description: 'Clean URLs by removing tracking parameters, UTM tags, and unnecessary query strings. Create clean, SEO-friendly URLs for free.',
    category: 'seo',
    tags: ['url', 'parameter', 'clean', 'tracking', 'utm'],
    keywords: ['URL parameter cleaner', 'URL cleaner', 'remove UTM parameters', 'strip tracking parameters'],
    icon: 'Filter',
    relatedTools: ['url-encoder-decoder', 'sitemap-generator'],
    phase: 3,
  },

  // ── Network Tools ─────────────────────────────────────────────────────────────

  {
    slug: 'internet-speed-test',
    name: 'Internet Speed Test',
    shortDescription: 'Check download & upload speed, latency, and jitter',
    description: 'Test your internet connection speed with our free online speed test. Measure download, upload, latency, and jitter using Cloudflare\'s network.',
    category: 'network',
    tags: ['speed', 'test', 'internet', 'bandwidth', 'latency', 'jitter'],
    keywords: ['internet speed test', 'network speed test', 'bandwidth test', 'connection speed', 'download speed', 'upload speed'],
    icon: 'Gauge',
    isPopular: true,
    relatedTools: ['ping-tool', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'address-lookup',
    name: 'IP Address Lookup',
    shortDescription: 'Get location, ISP, and timezone info for any IP',
    description: 'Lookup any IP address to find location, ISP, timezone, and more. Free IP geolocation service using ipapi.co.',
    category: 'network',
    tags: ['ip', 'address', 'lookup', 'geolocation', 'location', 'isp'],
    keywords: ['IP address lookup', 'IP geolocation', 'find IP location', 'IP info', 'ISP lookup', 'IP tracker'],
    icon: 'MapPin',
    relatedTools: ['dns-lookup', 'whois-lookup'],
    phase: 3,
  },
  {
    slug: 'dns-lookup',
    name: 'DNS Lookup',
    shortDescription: 'Query DNS records for any domain',
    description: 'Perform DNS lookups for A, AAAA, MX, TXT, NS, CNAME records using Google\'s DNS API. Free DNS query tool.',
    category: 'network',
    tags: ['dns', 'lookup', 'query', 'records', 'domain', 'nslookup'],
    keywords: ['DNS lookup', 'DNS query', 'DNS records', 'dig online', 'nslookup', 'DNS checker'],
    icon: 'Server',
    relatedTools: ['address-lookup', 'whois-lookup'],
    phase: 3,
  },
  {
    slug: 'http-headers-checker',
    name: 'HTTP Headers Checker',
    shortDescription: 'View and analyze HTTP response headers',
    description: 'Check HTTP response headers for any URL. View security headers, caching, content type, and more using AllOrigins API.',
    category: 'network',
    tags: ['http', 'headers', 'response', 'security', 'analyze'],
    keywords: ['HTTP headers checker', 'response headers', 'HTTP header analyzer', 'view headers', 'security headers'],
    icon: 'FileText',
    relatedTools: ['ssl-certificate-checker', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'ssl-certificate-checker',
    name: 'SSL Certificate Checker',
    shortDescription: 'Verify SSL/TLS certificates and security ratings',
    description: 'Check SSL certificate details, expiration, and security rating for any domain using SSL Labs API. Free SSL checker.',
    category: 'network',
    tags: ['ssl', 'certificate', 'tls', 'security', 'verify', 'expiry'],
    keywords: ['SSL certificate checker', 'SSL verification', 'TLS certificate', 'SSL test', 'certificate analyzer', 'SSL expiry'],
    icon: 'ShieldCheck',
    relatedTools: ['http-headers-checker', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'ping-tool',
    name: 'Ping Tool',
    shortDescription: 'Test network latency and connectivity',
    description: 'Ping any host or IP address to test network connectivity and measure latency. Free online ping tool with packet loss detection.',
    category: 'network',
    tags: ['ping', 'network', 'latency', 'connectivity', 'test', 'packet loss'],
    keywords: ['ping tool', 'network ping', 'latency test', 'ping online', 'connectivity test', 'packet loss'],
    icon: 'Activity',
    relatedTools: ['internet-speed-test', 'port-checker'],
    phase: 3,
  },
  {
    slug: 'port-checker',
    name: 'Port Checker',
    shortDescription: 'Check if ports are open or closed on servers',
    description: 'Check if a port is open or closed on any server. Test common ports (80, 443, 22, 21, etc.) or custom ports. Free port scanner.',
    category: 'network',
    tags: ['port', 'checker', 'scanner', 'network', 'tcp', 'open'],
    keywords: ['port checker', 'open port scanner', 'port test', 'network port check', 'TCP port checker'],
    icon: 'Server',
    relatedTools: ['ping-tool', 'website-status-checker'],
    phase: 3,
  },
  {
    slug: 'whois-lookup',
    name: 'WHOIS Lookup',
    shortDescription: 'Get domain registration and owner information',
    description: 'Lookup WHOIS information for any domain. Find registrar, creation date, expiration, and owner details using WhoisJSON API.',
    category: 'network',
    tags: ['whois', 'domain', 'registration', 'owner', 'registrar'],
    keywords: ['WHOIS lookup', 'domain WHOIS', 'domain registration info', 'WHOIS search', 'domain owner lookup'],
    icon: 'FileText',
    relatedTools: ['address-lookup', 'dns-lookup'],
    phase: 3,
  },
  {
    slug: 'website-status-checker',
    name: 'Website Status Checker',
    shortDescription: 'Monitor website uptime and availability',
    description: 'Check if a website is online or down. Monitor uptime, response time, and status codes using UpDown.io API. Free website monitoring.',
    category: 'network',
    tags: ['website', 'status', 'uptime', 'monitor', 'availability', 'down'],
    keywords: ['website status checker', 'website uptime', 'is website down', 'site status', 'uptime monitor', 'website availability'],
    icon: 'Activity',
    relatedTools: ['internet-speed-test', 'ssl-certificate-checker'],
    phase: 3,
  },
  {
    slug: 'url-redirect-tracer',
    name: 'URL Redirect Tracer',
    shortDescription: 'Follow and analyze HTTP redirect chains',
    description: 'Trace the full redirect chain for any URL. See all 301, 302, and other redirects with status codes and headers. Free redirect checker.',
    category: 'network',
    tags: ['url', 'redirect', 'tracer', 'chain', '301', '302'],
    keywords: ['URL redirect tracer', 'redirect checker', 'follow redirects', 'HTTP redirect chain', 'URL tracer', '301 redirect'],
    icon: 'ArrowRight',
    relatedTools: ['http-headers-checker', 'website-status-checker'],
    phase: 3,
  },
];

// ── Helpers ──────────────────────────────────────────────────────────

export const CATEGORIES: { value: ToolCategory; label: string; icon: string }[] = [
  { value: 'image', label: 'Image Tools', icon: 'Image' },
  { value: 'text', label: 'Text Tools', icon: 'Type' },
  { value: 'developer', label: 'Developer Tools', icon: 'Code2' },
  { value: 'converter', label: 'Converters', icon: 'ArrowLeftRight' },
  { value: 'generator', label: 'Generators', icon: 'Wand2' },
  { value: 'calculator', label: 'Calculators', icon: 'Calculator' },
  { value: 'security', label: 'Security', icon: 'Shield' },
  { value: 'seo', label: 'SEO Tools', icon: 'Search' },
  { value: 'network', label: 'Network Tools', icon: 'Globe' },
];

export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getRelatedTools(slug: string): Tool[] {
  const tool = getTool(slug);
  if (!tool?.relatedTools) return [];
  return tool.relatedTools
    .map((s) => getTool(s))
    .filter((t): t is Tool => t !== undefined);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.shortDescription.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q))
  );
}
